### ISSUE TITLE
request that the code also become open on github

### ISSUE THREAD

**Issue by dpastoor** [metrumresearchgroup/mrgsolve#1]
Hi Kyle et al,

This is an 'open' letter requesting that you consider making this code open. Though there aren't many of us, there is potential for more active collaboration, and issuing a pull request for a bug here is much more convenient than needing to go through the issue tracker but no code song and dance.

For example, a small but relevant issue,

```
Depends: R (>= 3.0.2)
Imports: Rcpp (>= 0.12.1), dplyr (>= 0.4.3), methods, magrittr (>=
        1.5), lazyeval (>= 0.1.10)
```

This will not work with a user on 3.0.2 as dplyr 0.4.3 itself shows:

```
Depends:
    R (>= 3.1.2)
```

Given the permissiveness of the CC license (awesome thanks!!) I'm just a little confused by the hesitance to host the source code in a place where others contribute.

**Comment by kylebmetrum** [comment]
Hi Devin - 

Thanks for the report; I updated the `R` dependency to match that of `dplyr`.  I need to get a new version out soon so that'll be in there.

I'll definitely bring the request back to our IS group.   All of our open source tools are under change control as a part of our QA process.  So the version that we make available (and the one we use for internal project work) is reviewed tested and documented before release.  We can look into ways of making that work with publicly hosted / available source.  Obviously it's in the best interest of the code base to get it out more frequently to users to test and improve and I like really that idea.  But the change control process requires some restriction at some point.

Thanks again for report and suggestions.

Kyle

**Comment by dpastoor** [comment]
Thanks for the response Kyle, appreciate the transparency.

Given that it seems you're following at least some version of semver, one other option could be to do something akin to how `data.table` versions where you have alternating stable and dev releases so people can actively contribute to the dev branch, while the stable branch can go through additional internal QA. 

It seems a lot of the QA could be mitigated through all pull requests going through CI system. That way any changes would automatically get run through the test suit and reported before you even had to look at the pull request. Eg easy to merge a passing request like: https://github.com/hadley/dplyr/pull/1570

but if it fails: https://github.com/hadley/dplyr/pull/1583 then the contributor can go back and fix before you'd need to address it.

Just food for thought. Look forward to future releases regardless!
