### ISSUE TITLE
carry.out DOSE with multiple dosing events has unexpected behavior

### ISSUE THREAD

**Issue by htjollyn** [metrumresearchgroup/mrgsolve#1166]
Hi

I have an issue with the following construction of events, where the intention is that every ID is uptitrated according to the scheme below.

`#STEP-UP Reg7 : 10mg QW / 30mg QW / 60mg Q3W`
`e1 <- ev(amt = 10, cmt=2, DOSE=10, REG_CODE = 7, addl=0, ii=7, rate=10/0.04)`
`e2 <- ev(amt = 30, cmt=2, DOSE=30, REG_CODE = 7, addl=0, ii=7, rate=30/0.04)`
`e3 <- ev(amt = 60, cmt=2, DOSE=60, REG_CODE = 7, addl=3, ii=21, rate=60/0.04) `
`e.iv.md.pop_reg7 <- as_data_set(seq(e1,e2,e3)) %>% ev_rep(1:nsub)`

After running the simulation with
`mod %>%  mrgsim_df(., delta=0.1, events = e.iv.md.pop_reg7, carry_out=c("DOSE", "REG_CODE"))`

The output is the following
![image](https://github.com/metrumresearchgroup/mrgsolve/assets/32710991/7afd8837-428b-43de-9fe4-ca61cf15b427)

The indicator variable DOSE switches incorrectly to 30 at time==0.1, which is the observation record after the dose. The amt arriving in CMT2, however, is correct (10).

Please advise what I am overlooking in order for this table to correctly display DOSE variable.

Thank you!

**Comment by kylebaron** [comment]
Hi @htjollyn  - 

Thanks for checking in. Like NONMEM, mrgsolve follows a [next observation carry backward approach](https://www.paganz.org/abstracts/investigations-of-the-representation-of-covariate-changes-in-nonmem/).  So what you are seeing is the expected behavior. The output is a little complicated because, in addition to this NOCB behavior, there is some decisions that need to be made around where to schedule observations when there is a dose at the same time. Passing `recsort = 3` and putting `evid` into the output will help see this:

``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter
nsub <- 1

e1 <- ev(amt = 10, cmt=2, DOSE=10, REG_CODE = 7, addl=0, ii=7, rate=10/0.04)
e2 <- ev(amt = 30, cmt=2, DOSE=30, REG_CODE = 7, addl=0, ii=7, rate=30/0.04)
e3 <- ev(amt = 60, cmt=2, DOSE=60, REG_CODE = 7, addl=3, ii=21, rate=60/0.04)
e.iv.md.pop_reg7 <- as_data_set(seq(e1,e2,e3)) %>% ev_rep(1:nsub)
mod <- house() 
mod %>% 
  mrgsim_df(., delta=0.1, events = e.iv.md.pop_reg7, 
            carry_out=c("DOSE", "REG_CODE", "evid"), recsort = 3) %>% 
  head()
#>   ID time evid DOSE REG_CODE GUT     CENT     RESP        DV        CP
#> 1  1  0.0    1   10        7   0 0.000000 50.00000 0.0000000 0.0000000
#> 2  1  0.0    0   30        7   0 0.000000 50.00000 0.0000000 0.0000000
#> 3  1  0.1    0   30        7   0 9.960082 49.64788 0.4980041 0.4980041
#> 4  1  0.2    0   30        7   0 9.910405 49.28282 0.4955203 0.4955203
#> 5  1  0.3    0   30        7   0 9.860977 48.98596 0.4930489 0.4930489
#> 6  1  0.4    0   30        7   0 9.811795 48.74495 0.4905898 0.4905898
```

<sup>Created on 2024-02-05 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

To reiterate: this is the behavior we expect to see. 

You have a couple of options to get `DOSE` to be what you'd like it to be: 

1 - Pass `nocb = FALSE` to `mrgsim()` this will do last observation carry forward instead of nocob; but be careful as this might have other unintended consequences
2 - Create a data set that includes doses and observations; this will take some of these decisions out of mrgsolve's hands and let you be specific about how you want them to behave. mrgsolve will still use `nocb` by default while simulating, but you'll have `DOSE` in place for you to use as I expect you want in to be used after the simulation. 

Hope this helps!

Kyle

**Comment by htjollyn** [comment]
Thank you very much for your reply Kyle.

I was aware of the NOCB behavior of MrgSolve, although I guess I expected event-specific information provided via ev() to be handled differently.
Thank you for providing the right context and potential solutions.

Best regards
Huybrecht

**Comment by kylebaron** [comment]
@htjollyn  - 

mrgsolve used to behave the way you desire. And it was convenient. But it was also inconsistent with other dataset. behavior, difficult to explain, and difficult to maintain. So we made a decision to go with consistency and stability. 

That said, I think I can implement a workflow that will give data items back in the simulated data with locf arrangement. Will work on that in the weeks to come.

**Comment by kylebaron** [comment]
@htjollyn BTW .... you can write the event object a little more conveniently; I mention it because this feature was added for exactly this use case. 

KTB


``` r
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

ev(amt = 10, cmt=2, DOSE = amt, REG_CODE = 7, addl=0, ii=7, rate=amt/0.04)
#> Events:
#>   time amt rate ii addl cmt evid DOSE REG_CODE
#> 1    0  10  250  7    0   2    1   10        7
```

<sup>Created on 2024-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
