### ISSUE TITLE
Include more function defs in nm-vars

### ISSUE THREAD

**Issue by kylebaron** [metrumresearchgroup/mrgsolve#1173]
Right now, we only have `LOG`, not `LOG10`

Included 

- `LOG10()` --> `log10()`
- `DEXP()` --> `exp()`
- `COS()` --> `cos()`
- `SIN()` --> `sin()`

**Comment by mattfidler** [comment]
In case you need a list of supported functions for `nm-vars`  there is one in the `nonmem2rx` parser syntax:

https://github.com/nlmixr2/nonmem2rx/blob/d74a4eef3a9c0211636cd0931f8424a2bd64e195/inst/abbrev.g#L233

I think I captured them all, but am unsure.

**Comment by kylebaron** [comment]
Thanks for sharing this, @mattfidler; very helpful. I'd like to find a way to tap into what you're doing with the nonmem parser some day; much more elegant than what I'm doing for now. 

Kyle

**Comment by mattfidler** [comment]
No problem Kyle, thought the function names might be helpful (it took me a bit to find from the `NONMEM` manual).

As far as the NONMEM translator, it translates directly to `rxode2`, so it may not be as useful for `mrgsolve` directly (unless we eventually figure out some translator, which is still on my internal backlog). 

However, the `nonmem2rx::nminfo()` may be useful for reading NONMEM by itself.  If I recall correctly you guys already have some of these utilities yourself (so it may not be useful).

However, if you decide to translate `monolix`, the `monolix2rx` parses most of the content to R first, so that may be useful if you want to include a translator from that direction (which I think is likely a long term project for you guys).

**Comment by kylebaron** [comment]
Included 

- `LOG10()` --> `log10()`
- `DEXP()` --> `exp()`
- `COS()` --> `cos()`
- `SIN()` --> `sin()`

**Comment by kylebaron** [comment]
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(mrgsolve)
#> 
#> Attaching package: 'mrgsolve'
#> The following object is masked from 'package:stats':
#> 
#>     filter

# KA != CL/V
modlib("pk1") %>% 
  param(CL = 0.391, V = 30, KA = 0.013) %>% 
  ev(amt = 100) %>% 
  mrgsim() %>% 
  as_tibble %>% 
  pull(CENT) %>% 
  summary
#> Building pk1 ...
#> done.
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   0.000   6.371  12.868  12.162  18.312  22.829

# KA = CL/V
modlib("pk1") %>% 
  param(CL = 0.39, V = 30, KA = 0.013) %>% 
  ev(amt = 100) %>% 
  mrgsim() %>% 
  as_tibble %>% 
  pull(CENT) %>% 
  summary
#> Loading model from cache.
#> Error in eval(expr, envir, enclos): k10 is too close to ka for analytical solution to one-compartment model.

# KA = CL/V
modlib("pk1") %>% 
  param(CL = 1, V = 20, KA = 0.05) %>% 
  ev(amt = 100) %>% 
  mrgsim() %>% 
  as_tibble %>% 
  pull(CENT) %>% 
  summary
#> Loading model from cache.
#> Error in eval(expr, envir, enclos): k10 is too close to ka for analytical solution to one-compartment model.
```

<sup>Created on 2024-05-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
