### ISSUE TITLE
Max on Initial compartment amount

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#12]
Unless there is a fundamental error in the model structure below, I think there may be a bug in how much amount can be entered as the initial value in a compartment. This is an example of a simple bacterial regrowth model with drug action

```
code <- '
$PARAM 
ke=0.2
kgrowth_b1=1.4 , kdeath=0.2 , emax=3 , ec50=10

$CMT B1 C

$SET delta=0.25

$ODE
dxdt_C = -ke*C;
dxdt_B1 = B1*kgrowth_b1 -(kdeath + eff)*B1;

double eff = emax*C/(ec50+C);

$CAPTURE B1

'

mod <- mread(code=code)
#works
mod %>% init(C=100,B1=10000) %>% mrgsim %>% View
#does not work
mod %>% init(C=100,B1=100000) %>% mrgsim %>% View
```

The error message for the second scenario is pasted below

```
DLSODA-  At current T (=R1), MXSTEP (=I1) steps   
      taken on this call before reaching TOUT     
In above message, I = 
[1] 2000
In above message, R = 
[1] 9.62941
DLSODA-  ISTATE (=I1) illegal.
In above message, I = 
[1] -1
DLSODA-  Run aborted.. apparent infinite loop.    
Error in tran_mrgsim(<S4 object of class "mrgmod">, data = 1, idata = list( : 
  error from XERRWD
```

**Comment by kylebmetrum** [comment]
````r
DLSODA-  At current T (=R1), MXSTEP (=I1) steps   
      taken on this call before reaching TOUT     
````

The solver is failing because maxsteps (default is 2000 ... I1 in the message) is too small.    

Try
````r
mod %>% init(C=100,B1=100000) %>% mrgsim(maxsteps=20000)
````

Or maybe more.

**Comment by kylebmetrum** [comment]
Also `$ODE` should (I think)  be:

`````r
$ODE
double eff = emax*C/(ec50+C); 
dxdt_C = -ke*C;
dxdt_B1 = B1*kgrowth_b1 -(kdeath + eff)*B1;

````

**Comment by kylebmetrum** [comment]
````r
#works
mod %>% init(C=100,B1=100000) %>% mrgsim(maxsteps=4000)
#does not work
mod %>% init(C=100,B1=100000) %>% mrgsim(maxsteps=3000)
# just to be safe
mod %>% init(C=100,B1=100000) %>% mrgsim(maxsteps=10000)
````

**Comment by vjd** [comment]
Thanks, could not interpret the message for MXStep.

Sure.. the order matters in $ODE.

**Comment by vjd** [comment]
How does Initial compartment amount relate to Maxsteps?

**Comment by kylebmetrum** [comment]
I responded too soon .... if out move `double eff = ...` up, you don't need to increase maxsteps; it will run at the default.  It was just choking because eff wasn't defined.

**Comment by vjd** [comment]
you are right..  sorry it was indeed a setup error from my side

**Comment by kylebmetrum** [comment]
Sometimes if the model is highly non-linear, it takes a lot steps to get to the next time point.  No particular connection to initial value.  You had delta=0.25 which is (appropriately) small ... so it should be less likely that the solver can't make it that far in 2000 steps.  Sometimes when you have observations that are far apart in time and the solver only has 2000 steps to take it can't make it; you can either increase maxsteps or put in some additional time points.


As a more general comment on this:
`mrgsolve` exits rather ungracefully when the solver fails and the messages from the solver aren't easy to deal with.  On my todo list to take a look at `istate` when the solver is done and try to be more helpful about what to do to fix it.  But on the upside, when I start getting complaints from the solver it is very frequently because I did something wrong in the model.  So a hard stop is almost better there ... forcing you to take another look at the code.

**Comment by vjd** [comment]
Thanks Kyle!

**Comment by kylebmetrum** [comment]
I'm not sure if we could or should suppress the messages coming out of DLSODA; but for now, when the solver returns with negative istate you will get a more-helpful message that is clearly from mrgsolve. (istate is 2 when the solver succeeds).

````
DLSODA-  At current T (=R1), MXSTEP (=I1) steps   
      taken on this call before reaching TOUT     
In above message, I = 
[1] 5
In above message, R = 
[1] 0.0009771848

mrgsolve: DLSODA returned with istate -1
  excess work done on this call; check the model or increase maxsteps.
````
