### ISSUE TITLE
How do you turn off a compartment?

### ISSUE THREAD

**Issue by JasonW000** [metrumresearchgroup/mrgsolve#128]
I am trying to implement flexibility of dosing of mono or combo therapy into a PK/PD model by using 2 different PK compartments, related to drug A and drug B.  In the case of monotherapy I believe I need to turn off one of the PK compartments since it appears to generate negative concentrations which may be affecting the PD.  How do I turn off the compartment relating to drug that is not dosed?  I tried setting cmt to negative in the ev record and this does not seem to work. 

I cannot find any mention of how to do this in the user guide. thanks.

**Comment by kylebmetrum** [comment]
You have to use `evid=2` with negative compartment number to turn it off (see attached).  

[Screen Shot 2016-09-22 at 5.44.40 PM.pdf](https://github.com/metrumresearchgroup/mrgsolve/files/488522/Screen.Shot.2016-09-22.at.5.44.40.PM.pdf)

You can try turning it off but I suspect that the the negative values (hopefully they are extremely small) are due to imprecision in the solver.  I recently ran into this with a viral dynamics model. 


Four options I can think of: 
  1. If you have an arm indicator for mono/combo, I ended up calculating the concentration for both and then setting the concentration to 0.0 based on the arm indicator.  
  1.  Set the concentration to zero if it goes negative ( `CP = std::max(0.0,CP)`)
  1. Lower the tolerances (`atol` down to `1E-20` or so; but this might freak out the solver ... and will cause the solver to do more work.)
  1. Turn the compartment off; might be worth a try.


It seems like `#2` would be easiest.  Obviously, only do this when you really think it is due to these numerical  / precision issues and not some bigger problem.

**Comment by kylebmetrum** [comment]
Did any of this help you?

**Comment by JasonW000** [comment]
I was able to implement #2 however I still see noise (although now only positive values) in 2 of the three PK compartments.  I cannot seem to turn of the compartments even though the dataset for mrgsim shows the following, which I thought would work based on your example.  I also tried different versions of this and nothing worked: 

ID evid time cmt amt
1    1    0   1   0
1    2    0  -1   0
1    2    0  -2   0
1    2    0  -3   0

Another concern is that when I dose into compartment 1 I see some contamination into compartment 2, such that the noise is significant enough to then show a PK time course in compartment 2.  See below

![image1](https://cloud.githubusercontent.com/assets/21269065/19162131/83fce89a-8bab-11e6-8143-b7d49c78e143.jpg)
![image2](https://cloud.githubusercontent.com/assets/21269065/19162136/88c66900-8bab-11e6-936e-b7487c620594.jpg)

**Comment by kylebmetrum** [comment]
I know it is unsettling to see this .... but it really is noise.  On my computer, `.Machine$double.eps` is `[1] 2.220446e-16` and the response is several orders of magnitude smaller than this.  So it's really zero.  I'm sure that the differentials for the second and third compartments evaluate to zero when you don't dose there so turning the compartment off won't do anything.  This isn't bleed through as if mass is leaking into a neighboring compartment, but numerical issues with the solver.  I see this from time to time with very tightly wound models or models where I have made a mistake in the coding (not saying there is a mistake here).  

FWIW ... I was able to code a model with three independent PK submodels with no problems.  I was expecting that and I know it doesn't help you at all.  Maybe we can dig into your model and see if we can identify anything?  Is there any part of the model that you can share privately with me via email?  Just the ODEs?  or more?  

You could try tweaking tolerances or step sizes in the solver but I don't have any suggestions for rational changes to make beyond the defaults.

**Comment by dpastoor** [comment]
@kylebmetrum how much overhead would adding a floor of 1e-16 or something around those lines to the output?

**Comment by kylebmetrum** [comment]
Yeah ... I think that could be a stop gap measure that I've done before.  But I always wonder if it is a clue about what is going on in the model.  

I took a look at the model code ... other pieces of the model are clearly challenging for the solver.  It seems that dropping `atol` to `1E-20` or so (default is `1E-8`) will give a clean run.  I guess it makes sense.

**Comment by kylebmetrum** [comment]
The model needed `atol=1E-50` or lower, but decreasing `hmax` to 0.01 or so seemed to do the trick as well.  This was a complicated, highly non-linear model with some discontinuity.  

I will open a new issue for enhancing the solver setting section in the user guide per @JasonW000 very reasonable request.
