### ISSUE TITLE
Getting the value of individual parameters from MAP estimation

### ISSUE THREAD

**Issue by MarioGS** [metrumresearchgroup/mrgsolve#144]
Hi,

I am playing a bit with mrgsolve and I have a silly question:

How can I get the values of the estimated individual parameter from MAP?

If I understood the vignette well we are optimizing the ETA. Thus, fit$par[1] returns the ETA for CL and fit$par[2] returns the ETA for V. I would expect getting the individual parameters as follow:

```
TVCL = 1.5*exp(fit$par[1])
TVV = 23.4*exp(fit$par[2])

```

However, it looks like this is not correct:

```
code <- '
$SET request=""
$PARAM TVCL=1.5, TVVC=23.4, ETA1=0, ETA2=0
$CMT CENT
$PKMODEL ncmt=1
$OMEGA 0 0
$SIGMA 0
$MAIN
double CL = TVCL*exp(ETA1 + ETA(1));
double V =  TVVC*exp(ETA2 + ETA(2));
$TABLE 
double DV = (CENT/V)*(1+EPS(1));
double ET1 = ETA(1);
double ET2 = ETA(2);
$CAPTURE DV ET1 ET2
'
mod <- mcode("map", code)
omega <- cmat(0.23,-0.78, 0.62)
omega.inv <- solve(omega)
sigma <- matrix(0.0032)

dose <- ev(amt=750,cmt=1)

sampl <- c(0.5,12,24)
set.seed(1012) 
sim <- 
  mod %>%
  ev(dose) %>%
  omat(omega) %>%
  smat(sigma) %>%
  carry.out(amt,evid,cmt) %>%
  mrgsim(end=-1, add=sampl)
sim
sim %<>% as.data.frame
y <- sim %>% filter(evid==0) %>% select(DV) %>% unlist %>% unname
y
data <- sim %>% select(-ET1, -ET2)
mapbayes <- function(eta,y,d,m,pred=FALSE) {

  sig2 <- as.numeric(sigma)
  eta %<>% as.list
  names(eta) <- names(init)
  eta_m <- eta %>% unlist %>% matrix(nrow=1)
  m %<>% param(eta)
  if(!pred) m %<>% obsonly
  out <- m %>% drop.re() %>% data_set(d) %>% mrgsim
  if(pred) return(out %>% as.tbl)
  sig2j <- out$DV^2*sig2
  sqwres <- log(sig2j) + (1/sig2j)*(y-out$DV)^2
  nOn <- diag(eta_m %*% omega.inv %*% t(eta_m))
  return(sum(sqwres) + nOn)
}

init <- c(ETA1=-0.3, ETA2=0.2)
fit <- newuoa(init,mapbayes,y=y,m=mod,d=data)
fit$par
slice(sim,1) %>% select(ET1, ET2)
pdata <- data %>% filter(evid==1)
pmod <- mod %>% update(end=24, delta=0.1) 
pred <- mapbayes(fit$par,y,pdata,pmod,pred=TRUE) %>% filter(time > 0)
head(pred)

########################################################################
#Check if individual parameters are properly computed
TVCL = 1.5*exp(fit$par[1])
TVV = 23.4*exp(fit$par[2])
mod <- param(mod, 
             TVCL = TVCL,
             TVV = TVV)
DOSE = 750
res = mod %>%
  ev(amt=DOSE) %>%
  update(end=24, delta=0.1) %>% 
  mrgsim(nid=1) %>%
  as.tbl() %>%
  filter(time>0)
res = dplyr::select(res,time,DV)
#Change the names
names(res) = c("TIME","DV")
test = res
########################################################################
ggplot() + 
  geom_line(data=pred, aes(time,DV),col="firebrick", lwd=1) + 
  geom_line(data=test, aes(TIME,DV),col="green", lwd=1) + 
  geom_point(data=data %>% filter(evid==0), aes(time,DV), col="darkslateblue",size=3)

```

I would expect that green and firebrick lines match each other. This is not the case! What am I doing wrong?

How should I compute the individual parameter instead?

Thanks,

Mario

**Comment by kylebmetrum** [comment]
Hi @MarioGS  - 

```r
mod <- param(mod, 
             TVCL = TVCL,
             TVV = TVV)
```

```r
> param(mod)

 Model parameters (N=4):
 name value . name value
 ETA1 0     | TVCL 1.5  
 ETA2 0     | TVVC 23.4 
```

The parameter name was `TVVC`, not `TVV`.  `mrgsolve` used to be more strict about this in the past but grown more lenient because it can be more flexible.  But I've been wondering about more options we can add to that update step to force a stop when you try to update a parameter that doesn't exist.  

When you type it `mod <- param(mod, KYLE = 12)` it should probably stop you from doing that.  But you probably need to let more stuff through when you pass a list or data frame in.  I'll look into changing this.

Kyle

**Comment by dpastoor** [comment]
@kylebmetrum In JS-land, a common technique is to just have a declaration of "use strict" to invoke such a thing.

What if there was either a block `$STRICT` (feels awkward but would be very clear where to put it, not a fan of turning options into blocks) or a annotation somewhere

$OPTIONS @strict  

or could go the opposite route, and by default use "strict mode", and only by explicitly declaring `@nostrict` or something would it give that flexibility for those that would be willing to accept the consequences. IMO, this approach actually feels better as it gives power users a flag, but 'protects' newer users from backing themselves into tricky debugging situation due to naming misconventions or otherwise.
