### ISSUE TITLE
Simulation output comparison to NONMEM

### ISSUE THREAD

**Issue by WangdaZ** [metrumresearchgroup/mrgsolve#217]
Dear All,

I am comparing the simulation output from mrgsolve and nonmem and found that the median (with 5th and 95th percentile) of the simulated values are slightly different with the two approaches. Does anyone have similar experience and comments on this?

Thanks,
Wangda

**Comment by kylebmetrum** [comment]
You have to post the code you are using;  the details (input, implementation, and output) matter if you are benchmarking against another program.  

Generally, you need to:

1. Use a fixed dataset that is identical for both the mrgsolve and NONMEM run; mrgsolve is convenient because you frequently don't need a fixed data set.  But if you are benchmarking and want to confirm that the answer is identical to several digits, you need to use a fixed data set.
1. Make sure the solver tolerances are identical for mrgsolve and NONMEM run
1. Make sure the number of digits in the answer are identical for the NONMEM and mrgsolve runs; in my my testing, I take 6 digits.  I don't know what the default is for NONMEM, so I code it into $TABLE.

**Comment by kylebmetrum** [comment]
Closing this without more specifics.  We know `mrgsolve` matches NONMEM for all compatible features.
