### ISSUE TITLE
Export data

### ISSUE THREAD

**Issue by jgonlop3** [metrumresearchgroup/mrgsolve#244]
Hi, I´m interesting on export data from a simulation output of the "complete example" - from: https://mrgsolve.github.io/2017/02/25/a-complete-example/ 

But R send this message error: 

> write.csv(out, 'out.csv')
Error in as.data.frame.default(x[[i]], optional = TRUE) : 
  cannot coerce class "structure("mrgsims", package = "mrgsolve")" to a data.frame

How can I solve it?

**Comment by dpastoor** [comment]
hi @jgonlop3, the output of an mrgsolve simulation is not a dataframe, rather a datastructure that contains the data, as well as other information about the model run. In order to write out the data to a csv, we first want to coerce the output to a dataframe, so you can do

as_data_frame(out)

also I would suggest using the write_csv from readr for more performant and consistent outputs, so you could do

```
write_csv(as_data_frame(out), "out.csv")
```

**Comment by jgonlop3** [comment]
This works perfectly. It´s incredible the quick and good answers this community offers. Thanks! this is the best support I have ever had!
