### ISSUE TITLE
different code output versus example

### ISSUE THREAD

**Issue by JSC67** [metrumresearchgroup/mrgsolve#275]
I was following along in the file introduction.pdf (pertinent to the 2016-03-12 tutorial) and found that the file intro_model.cpp needed to be modified before it would compile properly due to a deprecation.  Well and good; I compiled this:

```
// intro_model_v2.cpp
$PARAM CL = 1, VC = 10, WTKG = 80

$CMT CENTRAL

$MAIN
double CLi = exp(log(CL) + 0.75*log(WTKG/70) + ETA(1));

$OMEGA 0.04

$ODE
dxdt_CENTRAL = -(CLi/VC)*CENTRAL;

$TABLE
double DAY = floor(TIME/24);

$CAPTURE
DAY
```

and continued on and executed this and got what was shown below (ASIDE: I want to have this show up as R output, but the simple text editing tool Github provides doesn't preserve this when pasting nor when inserting a quote—any suggestions here?):

> out %>%
+     group_by(DAY) %>%
+     summarise(Amax=max(CENTRAL))
# A tibble: 6 x 2
    DAY        Amax
  <dbl>       <dbl>
1     0 1000.000000
2     1 1080.060057
3     2 1086.469671
4     3 1086.982825
5     4   87.023908
6     5    6.967139

But this is different from what the tutorial (introduction.pdf) shows on p. 11:

. Source: local data frame [6 x 2]
..
DAY Amax
. (dbl) (dbl)
. 1 0 1000.00000
. 2 1 1133.25386
. 3 2 1151.01045
. 4 3 1153.37659
. 5 4 153.69188
. 6 5 20.48004

I'm just curious: is this difference due to a bug that was fixed?  (If so, what?)

**Comment by dpastoor** [comment]
This is likely because you are drawing a different individual from the omega distribution

For example if you table out CL

$CAPTURE
DAY CLi

you'lll see each time you run it will be a different clearance.

I'd suggest setting a seed to get a consistent result.

**Comment by JSC67** [comment]
Actually, on p. 9 of the tutorial there is a set.seed(2192) step, which I did.  I should've mentioned that first.

**Comment by dpastoor** [comment]
did you run all lines of the tutorial from that point on before getting to your example code? 

Every time the RNG is invoked it keeps going, so, for example if another set of code had been run before your example, it would have moved from that seed already.

**Comment by JSC67** [comment]
Even if I repeat the code from the set.seed(2192) line, I get what I had, but it's entirely possible that some intervening code had been executed before the tutorial output was executed, so  your explanation may still be correct.  I'll assume this is the case and close this, but if you think that there may be more to it, please let me know.  Thanks.

**Comment by kylebmetrum** [comment]
@JSC67  @dpastoor The source code for this is now in a private repo.  But the `intro_model.cpp` was actually slightly different than what appeared in the slide (see also the attached).  
<img width="1027" alt="screen shot 2017-09-19 at 12 12 22 am" src="https://user-images.githubusercontent.com/16908301/30576946-d9c60388-9cd0-11e7-9d86-f201272443fa.png">


Try this model with the `2192` seed and you'll get the same answer as you see in the slides.  

```c
$PARAM CL=1, VC=10

$CMT CENT

$MAIN double CLi = exp(log(CL) + ETA(1));

$OMEGA 0.5

$ODE dxdt_CENT = -(CLi/VC)*CENT;

$TABLE capture DAY = floor(TIME/24);
```

Please remember that while this was a hands-on workshop, almost everything in the slide decks was set up so that I could *talk* about the material, illustrating this or that feature.  
I'm sure I added to the code chunk in the slide deck in order to have more to talk about and just didn't update the actual model file. But it was inconsequential for the purposes of this slide deck. 

It's ok to keep asking about output here, but the intention with the slide decks was really to teach concepts at the workshop.
