### ISSUE TITLE
Change assignment behavior for ev_assign

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#279]
Based on issue raised in #278 ; this really needs to change.  The assignment should be based on sorted unique values in the `evgroup` column,  not just the unique values.  

This change will also make us consistent with `as_deslist` type stuff, where designs get assigned based on a grouping value that is in the `idata_set`.

**Comment by kylebmetrum** [comment]
`as_deslist` behavior
https://github.com/metrumresearchgroup/mrgsolve/blob/master/R/class_tgrid.R#L94

**Comment by dpastoor** [comment]
hmm, I have one potential issues with this (not that the previous implementation handled it). I still think this may be too non-deterministic, in that the event context being joined is based on the unique values present at runtime, rather than a more proper key/value matching.

For example, given a subpopulation with a low prevalence, when generating values, if that group does not exist, I think, based on the code, it will error due to a mismatch, which is still definitely a reasonable protection but forces every group to always be present. Also, what if just splitting dataset before simulating.

df %>% split(.$SEX) %>% future_lapply/parallelroutine_of_choice(...)

what about an api that just considers 0 as a baseline value by default, so 

```
assign_ev(list(ev1,ev2), idata,"SEX", join=TRUE)
```

given sex is 0/1 would still work identically, but can have an additional argument like `start = 0`

but if you had like a RACE column where it was 1:4

```
assign_ev(list(ev1,ev2, ev3, ev4), idata,"RACE", join=TRUE, start = 1)
```

this would still be fine even if the dataset only had 1, 2, 4 in it.


The only problem with this is it assumes that everything is a factor that increments by 1, so if  for some reason there was a sequence of like 1, 3, 5 it would require something hacky like

```
assign_ev(list(ev1, NA, ev2, NA, ev3), idata,"weird", join=TRUE, start = 1)
```

so I don't know if this would have just a different, but equally problematic, set of issues.

**Comment by kylebmetrum** [comment]
It would probably be safest if the user was explicit about listing all of the unique values in `evgroup` and taking that order to match up with the order in the event list.  It might not always be super-easy or error-proof to come up with this, but at least it would be up to the user.  I would use names in the event list and use that to match up with unique values in `evgroup`, but I didn't like having numbers (potentially) as names for the list (I know you __can__ do it).

As far as low-prevalence groups go ... maybe there should be a different function or some additional argument that covers every single potential random draw.  The function was meant to assign different dosing interventions to, for example, treatment arms 1, 2, and 3.  Or "adults get one dose, adolescents get a different dose and peds get another dose".  If things are so random that you may or may not get adults in the population, `ev_assign` will let you know that it's time to try a different approach.  The change here seems reasonable to accommodate randomness "enrollment" (e.g the first patient was pediatric, not adult).  But for sure the function doesn't cover every possible thing that might happen.

**Comment by dpastoor** [comment]
off my head, thinking about the api that would feel nice to me for this might be like what about `join_ev` and make use of tibble list columns to store the evs


```
ev_grp <- data_frame(grp = c(0, 1), ev = list(ev1, ev2)))
join_ev(idata, ev_grp)
```

**Comment by kylebmetrum** [comment]
Nice and elegant.   Let's do `ev_join` instead?  (I think we were aiming for a series of functions with `ev_` prefix to group them together).  

And I think it will just be a wrapper around `ev_assign` that does some work to look at `ev_grp` and `idata` and get that input into the right shape to pass off?  Maybe there is a more-elegent way to put it all together.  I can't tell at this point whether `ev_assign` is hacky or not.

**Comment by dpastoor** [comment]
yes brainfart on my end, definitely should keep a consistent api. Don't have too much time to think about it right now as I'm at T-minus 1 week to dissertation submission (finally). Will circle back and take a stab at it if you haven't gotten around to it by the time I can have a spare moment.
