### ISSUE TITLE
Calculate population mean Cmin with Mrgsolve output functions

### ISSUE THREAD

**Issue by WangdaZ** [metrumresearchgroup/mrgsolve#295]
Hi All, 
I am trying to calculate the population mean Cmin with Mrgsolve output functions, which works with reactive data frame. 

library(dplyr)
 mrgsolve:::house()
 out.cmax<-mod %>% 
  ev(amt=100) %>%
  mrgsim %>% 
  filter(time >=10) %>%  
  group_by(ID) %>%
  summarise(Cmin=min(DV))

The code above calculates the overall minimal concentration. Is there similar function allows to calculate the mean and 95CI of Cmin, which can directly publish by "renderTable" for shiny.

Thanks,
Wangda

**Comment by dpastoor** [comment]
Wangda, 

This actually is nothing specific to mrgsolve, you can just use dplyr (as you are using for summarize)

In this case you have all coins by I’d, and you can extend this at this point

```
library(tidyverse)
q05 <- partial(quantile, probs = 0.05) # this is creating a q05 function that
# only needs x to calculate the 5th percentile, you can do this for q50 q95 etc too)

# your code
... %>% summarize(cmon = min(DV)) %>% 
# lets do some additiona derivations, we can apply a bunch of
# functions at a specific column using mutate_at
summarize_at(vars(cmin), funs(min, q05, q50, mean, q95, max))
```

That would further calculate the min, 5th percentile, median, mean, 95th percentile and max value for cmin 

Again, this is not something built in to mrgsolve, but leveraging the additional functionality of dplyr and the tidyverse, which you can look into for more functionality.

**Comment by kylebmetrum** [comment]
@WangdaZ This should be something along the lines of what @dpastoor suggested.  I filled in the example a bit so that there would be replicate `Cmin` on which to calculate the mean and 95% CI.  



Load the model and put something in `$OMEGA`
============================================

``` r
library(dplyr)
library(mrgsolve)

mod <- mrgsolve:::house() %>% omat(dmat(rep(0.1, 4)))

revar(mod)
```

    . $omega
    . $...
    .         [,1] [,2] [,3] [,4]
    . ECL:     0.1  0.0  0.0  0.0
    . EVC:     0.0  0.1  0.0  0.0
    . EKA:     0.0  0.0  0.1  0.0
    . EKOUT:   0.0  0.0  0.0  0.1
    . 
    . 
    . $sigma
    . $...
    .        [,1]
    . EXPO:     0

Create a batch to simulate (`idata_set`)
========================================

``` r
idata <- data_frame(ID = 1:1000)
```

I usually make a function to do the confidence interval
=======================================================

1.  First, just calculate the 95% CI (`ans`)
2.  Then return something that  looks nice

``` r
ci <- function(x,digits = 3) {
  
  ans <- quantile(x,c(0.025,0.975))
  
  paste0("[",paste(signif(ans,digits), collapse = ", "),"]")
}

ci(rnorm(1E6))
```

    . [1] "[-1.96, 1.96]"

Ok, go
======

1.  Pass in an `idata` set to simulate a population
2.  Again, group by `ID` and calculate `Cmin` (like you did)
3.  Next, ungroup and summarise again, calculating the mean and CI

``` r
out <-
  mod %>%
  ev(amt = 1000) %>%
  mrgsim(idata = idata, end = 24) %>%
  filter(time >= 10) %>%
  group_by(ID) %>%
  summarise(Cmin = min(DV)) %>%
  ungroup %>%
  summarise(Mean = signif(mean(Cmin),3), CI = ci(Cmin), N = n())
```

``` r
out
```

    . # A tibble: 1 x 3
    .    Mean           CI     N
    .   <dbl>        <chr> <int>
    . 1    15 [4.66, 26.5]  1000

**Comment by WangdaZ** [comment]
Thanks@dpastoor @kylebmetrum. Both approaches worked. 
P.S. in case the codes above doesn't work for you, try 
detach("package:plyr", unload=TRUE)
