### ISSUE TITLE
Body weight based dosing events

### ISSUE THREAD

**Issue by WangdaZ** [metrumresearchgroup/mrgsolve#302]
Dear Kyle and all,

I am trying to simulation PK with WT based dosing (2mg/kg as example). Using house model as example below:
###works fine with 2mg dosing with 3 different ii
mod <- mrgsolve:::house()
idata <- 
  data_frame(ID=1:10) %>% 
  mutate_random(WT[50,100] ~ rnorm(70,10))
ev1 <- ev(time=0,amt=2, cmt=1, ii=5, addl=1)
ev2 <- ev(time=10,amt=2, cmt=1, ii=10, addl=1)
ev3 <- ev(time=30,amt=2, cmt=1, ii=20, addl=1)
out<-mod %>%
  ev(ev1+ev2+ev3) %>%
  idata_set(idata) %>%
  mrgsim
out.df<-as.data.frame(out)
plot(out, CP~.)

###when I change the simulation dataset as below, it gives me two more row at each time slot I didn't want. Is this from ii not starting at the intended time?

data.dose <- ev(ev1+ev2+ev3)
data.dose<-as.data.frame(data.dose)
data.all<-merge(idata,data.dose)
data.all$amt<-data.all$WT*data.all$amt
out.wt<-mod %>%
  data_set(data.all) %>%
  idata_set(idata) %>%
  mrgsim
out.df.wt<-as.data.frame(out.wt)
plot(out.wt, CP~.)

From the dataframe view, everything looks right. Not sure where the unwanted rows from.
I think it was probably discussed before the best way to implement WT base dosing, but I didn't find a good example in the forum. Please let me know what went wrong and the good coding for WT based dosing events.

Thanks,
Wangda

**Comment by reejbee** [comment]
Hi Wangda, 

 In your data_set (data.all) you have repeat events for IDs that are not sorted. If mrgsim sees an ID column 1:10, followed by a 1 again it assumes a new individual to simulate. 
Try this for your simulation code and see if this is what you are looking for: 

out.wt<-mod %>%
  data_set(data.all %>% **arrange(ID,time)) %>%**
  #idata_set(idata) %>% ## You don't need this line since weights are already in "data.all" 
  mrgsim

 - Rena

**Comment by WangdaZ** [comment]
Hi Rena,

It works now. Thanks for the help.

Best,
Wangda
