### ISSUE TITLE
PKNCA Data Link

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#303]
I've recently been working on some automated data management code ([/billdenney/pknca.portation/](/billdenney/pknca.portation/)).

The code is still young (only use it right now if you're confirming that you're getting what you expect), but one common use case that I've found is the need to do simulations in `mrgsolve` and then do NCA on the output.

To do this, I'd need a bit more information than is currently in the typical mrgsolve output.  Specifically, I'd need dose information (though I've not looked in detail to confirm that's the only thing needed).  In general, I'd like to enable the following style of code:

```r
model %>%
  mrgsim() %>%
  as.PKNCAdata() %>%
  pk.nca()
```

My specific questions are:

* Is there a guaranteed way to extract the dosing information from an `mrgsim` result (even if `evid` is not put in the output)?
* Is there an obvious way to detect the (most common) concentration data?
    * With most of the examples, CENTRAL or CENT are the typical plasma PK compartments.  Is there a way to almost certainly get the right compartment?
    * Is there a way to detect that I'm not getting the right compartments? (e.g. What if multiple drugs are simulated simultaneously-- I'd need additional input, and I'd like to be able to detect that.)
* Are there other hiccups that you can think of that may apply for an automated mrgsolve-PKNCA link?

**Comment by dpastoor** [comment]
not to answer this atm, but at least one thing that you could also consider is to to also 'take control' over the simulation settings before the simulation occurs

```
model %>%
    augment_nca() %>%
   mrgsim()
```

or even

```
model %>% 
   nca_sim()
```

That way you can control the request object and do additional introspection to ask for certain things before the simulation occurred.

**Comment by billdenney** [comment]
@dpastoor, I like the `augment_nca` idea!  `nca_sim` assumes that I'll know a lot about the internals of mrgsolve and the simulation that may change over time (i.e. `augment_nca` could be in my package; `nca_sim` would need to be in `mrgsolve`).

I'm agnostic to where the functions go, but I'm trying to make `PKNCA.portation` into a good, generic model-ready dataset creator, so I'd like to avoid replacing functions in other packages (meaning, replacing mrgsim with nca_sim seems like it could increase maintenance).

**Comment by kylebmetrum** [comment]
Sorry I'm just getting to this.   I like the `augment_nca` idea too.  It seems like it has the least baggage to carry around. 

# Detecting concentration data
* We almost never give any significance to compartment or parameter names, so I would think it would be hard to make a guess beyond saying "if we find `CENT` we'll use it otherwise please tell us which compartment to use".  That could be an argument to `augment_nca`. 
* Also, we never have any automatic scaling; would you have to ask people for `CP` instead?

# Extracting dose information
This will be complicated ... I think you would need to set some requirements for input data at some point, not sure.  

Some thoughts:

I wonder if we could use `tad` here.  We can always programmatically force mrgsolve to give us `evid` and `amt`.  When you simulate with `tad = TRUE`, you will be able to see dosing records (even those that are scheduled via `addl` __as long as there is an observation record there as well__).  

``` r
library(rbenchmark)
library(dplyr)
library(mrgsolve)
mod <- mrgsolve:::house()


data(extran1)
data(extran3)
data <- extran1

out <- mrgsim(mod, data = data, end = 240, 
              tad = TRUE, carry.out = "amt,evid")

filter(out, evid==1 | tad==0)
```

    . # A tibble: 19 x 10
    .       ID  time   tad  evid   amt          GUT     CENT     RESP       DV
    .    <dbl> <dbl> <dbl> <dbl> <dbl>        <dbl>    <dbl>    <dbl>    <dbl>
    .  1     1     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  2     1     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    .  3     1    24     0     0     0 1.000000e+03 314.2896 19.14896 15.71448
    .  4     1    48     0     0     0 1.000000e+03 408.9518 16.14837 20.44759
    .  5     1    72     0     0     0 1.000000e+03 437.4635 15.42059 21.87318
    .  6     2     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  7     2     0     0     1  1000 0.000000e+00   0.0000 50.00000  0.00000
    .  8     3     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  9     3     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    . 10     3    24     0     1   500 5.000000e+02 314.2896 19.14896 15.71448
    . 11     3    48     0     1   500 5.000000e+02 251.8070 21.82593 12.59035
    . 12     3    72     0     1  1000 1.000000e+03 232.9876 22.78535 11.64938
    . 13     4     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    . 14     4     0     0     1  2000 0.000000e+00   0.0000 50.00000  0.00000
    . 15     4    48     0     0     0 0.000000e+00 311.7580 19.24459 15.58790
    . 16     4    96     0     0     0 0.000000e+00 340.0401 18.22762 17.00200
    . 17     5     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    . 18     5     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    . 19     5    24     0     1  5000 3.144519e-10 314.2896 19.14896 15.71448
    . # ... with 1 more variables: CP <dbl>


This might also be an option ... modifying the input so that it will be more-friendly to deal with after simulation:

``` r
realize_addl(data)
```

    .    ID  amt cmt time addl ii rate evid
    . 1   1 1000   1    0    0  0    0    1
    . 2   1 1000   1   24    0  0    0    1
    . 3   1 1000   1   48    0  0    0    1
    . 4   1 1000   1   72    0  0    0    1
    . 5   2 1000   2    0    0  0   20    1
    . 6   3 1000   1    0    0  0    0    1
    . 7   3  500   1   24    0  0    0    1
    . 8   3  500   1   48    0  0    0    1
    . 9   3 1000   1   72    0  0    0    1
    . 10  4 2000   2    0    0  0  100    1
    . 11  4 2000   2   48    0  0  100    1
    . 12  4 2000   2   96    0  0  100    1
    . 13  5 1000   1    0    0  0    0    1
    . 14  5 5000   1   24    0  0   60    1


``` r
out <- mrgsim(mod, data = realize_addl(data), end = 240, 
              tad = TRUE, carry.out = "amt,evid")

filter(out, evid==1 | tad==0)
```

    . # A tibble: 19 x 10
    .       ID  time   tad  evid   amt          GUT     CENT     RESP       DV
    .    <dbl> <dbl> <dbl> <dbl> <dbl>        <dbl>    <dbl>    <dbl>    <dbl>
    .  1     1     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  2     1     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    .  3     1    24     0     1  1000 1.000000e+03 314.2896 19.14896 15.71448
    .  4     1    48     0     1  1000 1.000000e+03 408.9518 16.14837 20.44759
    .  5     1    72     0     1  1000 1.000000e+03 437.4635 15.42059 21.87318
    .  6     2     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  7     2     0     0     1  1000 0.000000e+00   0.0000 50.00000  0.00000
    .  8     3     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    .  9     3     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    . 10     3    24     0     1   500 5.000000e+02 314.2896 19.14896 15.71448
    . 11     3    48     0     1   500 5.000000e+02 251.8070 21.82593 12.59035
    . 12     3    72     0     1  1000 1.000000e+03 232.9876 22.78535 11.64938
    . 13     4     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    . 14     4     0     0     1  2000 0.000000e+00   0.0000 50.00000  0.00000
    . 15     4    48     0     1  2000 0.000000e+00 311.7580 19.24459 15.58790
    . 16     4    96     0     1  2000 0.000000e+00 340.0401 18.22762 17.00200
    . 17     5     0     0     0     0 0.000000e+00   0.0000 50.00000  0.00000
    . 18     5     0     0     1  1000 1.000000e+03   0.0000 50.00000  0.00000
    . 19     5    24     0     1  5000 3.144519e-10 314.2896 19.14896 15.71448
    . # ... with 1 more variables: CP <dbl>

**Comment by billdenney** [comment]
@kylebmetrum, It is taking me longer to re-reply.  No worries. :)

I'm more hopeful after reading your message that automatic (or at least user-assisted, semi-automatic) NCA linking is possible.

For the concentration, I would need to get a value that is likely to be the scaled central compartment concentration.  For that, I could start by lookin for a common parameter name choosing the first of `CP`, `CENT`, or `CENTRAL`.  If specified by the user, no automatic search would be performed (just a confirmation that it will be in the output).  Before the simulation is run, is there a straight-forward way to determine the names of all values that will be returned?

For dosing, I think that I could just extract all appropriate `evid` rows from the input rather than relying on them being replicated with an observation record in the output.

Is there a good way to add an attribute to the model object that would be carried through to the simulation object?

**Comment by kylebmetrum** [comment]
Hi @billdenney - 

Just a quick response.  Will continue to think about it. 

Kyle


-   [Find names](#find-names)
    -   [Method 1](#method-1)
    -   [Method 2](#method-2)
    -   [Method 3](#method-3)
-   [Pass an attribute](#pass-an-attribute)

``` r
library(mrgsolve)

mod <- mread("pk1", modlib())
```

    ## Compiling pk1 ... done.

Find names
==========

Method 1
--------

``` r
cols <- names(mrgsim(mod, end = -1, add = 0))

cols
```

    ## [1] "ID"   "time" "EV"   "CENT" "CP"

Method 2
--------

`as.list.mrgmod` isn't super fast ... it returns a bunch of stuff

``` r
x <- as.list(mod)
cols <- c(x$cmt,x$capture)

cols
```

    ##                   CP 
    ##   "EV" "CENT"   "CP"

Method 3
--------

I can provide a formal way to get the captured names

``` r
cols <- c(names(init(mod)), mod@capture)
cols
```

    ##                   CP 
    ##   "EV" "CENT"   "CP"

Pass an attribute
=================

-   Again, there used to be a formal, exported method for getting the model object out of the object for simulated data
-   I can re-export it or find some stable way to get the model object back instead of snooping into the object (maybe a single exported list of accessor functions).

``` r
attr_mod <- structure(mod, stuff = list(a = 1, b = 2, c = 3))

out <- mrgsim(attr_mod)

attr(mrgsolve:::mod(out), "stuff")
```

    ## $a
    ## [1] 1
    ## 
    ## $b
    ## [1] 2
    ## 
    ## $c
    ## [1] 3

``` r
attr(out@mod, "stuff")
```

    ## $a
    ## [1] 1
    ## 
    ## $b
    ## [1] 2
    ## 
    ## $c
    ## [1] 3

**Comment by billdenney** [comment]
@kylebmetrum, Thanks for the quick response!

For extracting the returned names, Method 1 seems simple and likely to be stable.

For the attributes, I think that a formal model extractor would be preferred to me (and generally may be useful to others).  Perhaps an "as.mrgmod" function that can operate on simulation results?

**Comment by kylebmetrum** [comment]
@billdenney 

Just to make sure we're talking about the same things here: I think the burden of adding an attribute to the model object and getting it back after the simulation would still be on the programmer (you). Is that right?  I sort of floated the attribute idea as a quick way to do it.  But you could do something more formal than that just as easily. 

The question is around how do you go get the model out of the simulation output object?
We used to have an exported api for digging into the model object and the simulation output object.  It just got to be too many functions and lots of stuff in the namespace.  Plus, the vast majority of them were something along the lines of:

```r
mod <- function(x,...) UseMethod("mod")
mod.mrgsims <- function(x...) x@mod

out <- mrgsim(mod)

mod(out)
```

Almost all of the api functions still exist (I use them under the hood) but they aren't exported.  I 
personally wish there was a way to make a set of functions like this available as a public resource,
 but just not have to dump them out into the working namespace ... something similar to
 `mrgsolve:::mod(out)` in that the function isn't cluttering the environment but different in that the
 function is expected to be used by the public, is documented and maintained etc.  I don't know how
 to replicate this behavior. 


I thought about making some generic extractor (a single function) where you name the item that you want to get out. Since these are `S4` objects, there already is an interface for this.  The big benefit IMO is that it will fail if you ask for something that doesn't exist.  But I think it might be enough of an interface because (almost) all of the slots are simple ... once you get what is in the slot, there isn't any other data structure that might change on you or that you have to figure out.

```r
> mod <- mread("pk1", modlib())
Compiling pk1 ... done.
> 
> out <- mrgsim(mod)
> 
```

These all do pretty much the same thing. 
```r
> the_mod <- getElement(out, "mod")
> 
> the_mod <- methods::slot(out, "mod")
> 
> the_mod <- out@mod
> 
> mod <- function(x,...) UseMethod("mod")
> mod.mrgsims <- function(x,...) x@mod
> 
> the_mod <- mod(out)
```

And the slots are documented
```r
?`mrgsims-class`
```

Working through Rs `slot` function will fail if that slot goes away at some point.  
```r
> doesnt_exist <- getElement(out, "something")
Error in methods::slot(object, name) : 
  no slot of name "something" for this object of class "mrgsims"
> 
> out@something
Error: no slot of name "something" for this object of class "mrgsims"
> 
> methods::slot(out, "something")
Error in methods::slot(out, "something") : 
  no slot of name "something" for this object of class "mrgsims"
> 
```

**Comment by billdenney** [comment]
@kylebmetrum, I think that this discussion went afield of the original request.

Getting back to the basics of the question, I think that I know (most of) what I need to know to get started, and I think that I can do everything at the end (so `augment_nca` won't be required, everything can be done after the simulation is complete).

Starting from the example that you just gave:

```r
mod <- mread("pk1", modlib())
out <- mrgsim(mod)
```

**Extracting Dose Info**

I think that all dosing info is stored in `out@mod@events` filtering for EV = 1 or 4.  I will need to account for "ADDL" and "II".

**Extracting Concentration Info**
`as.data.frame(out) %>% filter(EV %in% 0)` (or "EV" = "EV", "EVID", or "evid").  If not given the column name for concentration, guess the right one as the first available of "CP", "CENTRAL", or "CENT".

**Grouping Info**

Information on how to group data together to define the columns that separate a subject and other grouping parameters (e.g. dose, treatment name, etc.) will probably need to come from the user.  The default would be the column name "ID".

_Are there any other variables that should be automatic grouping variables?_

**Comment by kylebmetrum** [comment]
Hi @billdenney 


## Regarding upper / lower case

Start with `time` / `TIME`:

- It is either `time` or `TIME`; if `time`, all of the other "nmtran" 
type data items need to be lower case; if `TIME`, all other "nmtran" 
type data items need to be upper case

- Then it is either `EVID` or `evid`
- And either `AMT` or `amt`
- And either `II` or `ii`
- And either `ADDL` or `addl`

- It's an error if you have (for example) `amt` and `AMT`
- It's an error if you have `TIME` and `amt`

## Extracting Dose info
- See above on upper/lower case

- `out@mod@events` is going away; storing the event object in the model is
left over from very early (very different) mrgsolve.  And it's not really 
consistent with the whole setup at this point. 

- If you can't carry anything (like the input data) along as an 
attribute to the model object, you might force the dosing info 
into the output by adding it to `carry.out`.  You'd have to cover your 
bases in terms of lower/upper case then.  But if you're spending time
getting the data ready, maybe go in once and change those columns
to either all upper or all lower case ... probably lower case
since that is how the event objects come in.



## Extracting Concentration Info
- I would grab `EVID 0` and `EVID 2` just in case
- What to guess: there is no standard to draw on; since we 
need something scaled, I would tend not to look at `CENT` or 
`CENTRAL` but go for `CP` or `DV`.  Sort of depends on what people
like to do.

## Grouping
- Agree on your assessment; I don't see anything else coming 
out of `mrgsolve`

**Comment by billdenney** [comment]
Hi @kylebmetrum,

Thanks!  I think that I'm almost where I need to be.

One remaining question:  "`out@mod@events` is going away"  Are events stored anywhere else in the simulation object?  Everything else that we're discussing, I can get from the simulation object, so that would simplify the process not to have to do any pre-treatment before running the simulation.

**Comment by kylebmetrum** [comment]
@billdenney Events are currently stored, but the goal moving forward is to not store them in the model object.  One problem is that it would only work for event objects, not data sets.  And if we wanted to keep all of that around, we'd have to stash a bunch more stuff.  We could think of a flag that would automatically capture the input data, but then you'd have to make sure that flag was set too.

But there are places in the model object where you could store stuff. I put some ideas below.  IMO, this is still the way to go ... you'll get a chance to check, validate, impose restrictions prior to the run and it'd make your life easier once the simulation is over. 



But ... The more I look at this, the more it seems natural to either pre-process to get the inputs
right / captured or just take control of the simulation.  I agree that it'll be some work, but 
maybe not as much work as taking any and every simulated data object and getting the 
information you need.  




``` r
library(mrgsolve)


mod <- mread("pk1", modlib())
```

    ## Compiling pk1 ... done.

``` r
data <- as.data.frame(ev(amt = 100, ID = 1))
```

Quick / dirty?
==============

This function in PKNCA
----------------------

-   not sure if this is what you were planning, but I'd force the user to pass the input here

-   this might seem a little hacky, but it is exactly what `data_set` is doing (i.e. [here](https://github.com/metrumresearchgroup/mrgsolve/blob/master/R/data_set.R#L105)) ... so likely to be stable

``` r
augment_nca <- function(mod, data) {
  mod@args$PKNCA_data <- data
  data_set(mod, as.data.frame(data))
}
```

Do the simulation
-----------------

``` r
out <- 
  mod %>% 
  augment_nca(data) %>% 
  mrgsim
```

``` r
head(out)
```

    ## Model:  pk1

    ##   ID time         EV     CENT       CP
    ## 1  1    0   0.000000  0.00000 0.000000
    ## 2  1    0 100.000000  0.00000 0.000000
    ## 3  1    1  36.787944 61.40526 3.070263
    ## 4  1    2  13.533528 81.00022 4.050011
    ## 5  1    3   4.978707 85.36010 4.268005
    ## 6  1    4   1.831564 84.25422 4.212711

get the stuff back
------------------

``` r
simargs(out@mod)
```

    ## $PKNCA_data
    ##   ID time cmt amt evid
    ## 1  1    0   1 100    1

There is also an environment that we could take advantage of
============================================================

There is an api for dealing with the environment, just no capability (right now) for **adding** stuff to the environment

I could add this to `mrgsolve`
------------------------------

``` r
env_add <- function(.x, .as, ..., .dots = list()) {
  .as <- as.character(.as)
  assign(.as, c(.dots, list(...)), envir = .x@envir)
  .x
}
```

This function in PKNCA
----------------------

``` r
augment_nca <- function(mod, data) {
  mod <- env_add(mod, .as = "nca_stuff__", the_data = data)
  data_set(mod,data)
}
```

Do the simulation
-----------------

``` r
out <- 
  mod %>% 
  augment_nca(data) %>% 
  mrgsim
```

get the stuff back
------------------

-   these pieces are already functional

``` r
my_stuff <- env_get(out@mod)[["nca_stuff__"]]
my_stuff
```

    ## $the_data
    ##   ID time cmt amt evid
    ## 1  1    0   1 100    1

``` r
env_ls(out@mod)
```

    ##        object class
    ## 1 nca_stuff__  list

**Comment by kylebmetrum** [comment]
@billdenney thinking about this over lunch ... seems easier to me now to just 
write a wrapper around `mrgsim` as @dpastoor suggested.  It just doesn't seem to be more work or risk.  And it seems like it's the place where you'd want to have control ... you get the last say on what happens to the data / model prior to simulating.  If you pre-process the model or data, 
the user could fiddle with it prior to calling `mrgsim`.  

```r
simnca <- function(x, data = NULL, events = NULL, ...) {
  
  # Do what you need to do to check 
  # on data, events, etc ....
 
  # then simulate as if nothing happened
  mrgsim(x, data = data, events = events, ...) 
  
}
```

**Comment by billdenney** [comment]
@kylebmetrum, as I've been thinking over it today, I think that I came to a similar conclusion that direct extraction of events is not the simplest with just the simulation results.  I think the path that I'll take will be:

* an `mrgsims` object is usable as concentration-time data (using it in a `PKNCAconc` call.
* Dosing data can come from the events put into the model, but they will be gathered separately.

Given our conversation within the thread, I think that's the simplest method to both be easy for the user and be future-proof for new versions of mrgsolve.
