### ISSUE TITLE
Feature Request:  Control Rate of Infusion Dynamically in $ODE

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#341]
Similar to a question I recently posed on NMUSERS (https://cognigencorp.com/nonmem/current/2018-March/6993.html), is it possible to control the input rate to a compartment in the `$ODE` block?

Specifically, I have a problem with apparent time-varying bioavailability during a long intravenous infusion (due to potential saturable adsorption of drug in the catheter).  During the infusion, I'd like to be able to control the rate of infusion via the equivalent of a time-varying bioavailability to account for the saturable adsorption.

The main issue that I have is that I can't introduce discontinuities at arbitrary times in the modeling (that I know of).  This has led to my attempt to simulate it to this point having integration failing on the second dose.

**Comment by kylebmetrum** [comment]
@billdenney This probably isn't what you really want.  But maybe it'll work as a starting point to get us there.  I can make changes to the example if I'm using some setup or making some assumption that you don't have access to in your case.  If there is just no way to do want you want to do without introducing some discontinuity, then just disregard until that get's worked out. 

I'm doing an infusion here because mrgsolve will automatically schedule the "infusion-off" event creating a discontinuity when the infusion is scheduled to end.  In the meantime, I'm creating a "correction factor" for the rate to account for losing drug on the IV set.  Again, maybe not your setup, but can you adapt here to do what you want to do? 

The other approach is to use two `evid=2` records in the data set, one to mark the start of the infusion and the other to mark the end.  Then you can fiddle with rate all your want.  No discontinuities for the bumps  in rate there, so maybe it won't hold up.  

Anyway, your mileage may vary with this ....

``` r


library(mrgsolve)

e <- ev(amt = 10, rate = -2, ii = 240, addl = 2)


code <- "
$PARAM CL = 1, VC = 30

$CMT CENT

$MAIN

if(NEWIND <= 1) {
capture rate = 0;
}

D_CENT = 60;

if(EVID==1) {
rate = self.amt/D_CENT;
bool infusion_on = true;
double dose_time = TIME;
}

if(EVID==9) {
rate = 0;
infusion_on = false;
}

$ODE

double rate_correction = (SOLVERTIME-dose_time)*0.01*rate;

dxdt_CENT =  -(CL/VC)*CENT - rate_correction;

$TABLE
capture effective_rate = rate - rate_correction;
"

mod <- mcode("foo", code)
#> Compiling foo ... done.

mrgsim(mod, events = e, end = 600, delta = 0.1) %>% plot()
```

![](https://i.imgur.com/ck6s7gV.png)

**Comment by billdenney** [comment]
@kylebmetrum, That looks like it would work for my current setup.  I hadn’t seen EVID 9 before.  Is that new?

**Comment by kylebmetrum** [comment]
It's always been there, but always used internally.  When an infusion starts, we have to insert another record object to end the infusion at the right time; that's `EVID 9`.  

I can put `rate` into that `self` object.  But what I think would be most helpful here is to just pass the (actual, total, current) infusion rates into `$ODE`;  with a little more coding, we could give you the option of adding the infusion rate (or a modified version of that) to the appropriate equation;  but it might be just as good to keep adding the infusion to the equations under the hood and just let you add or subtract in `$ODE`, potentially as a function of the current actual rate.  I think the most dangerous setup would be to allow the user to modify the rate.  

Or ... maybe there is another evid that will create discontinuities at `time` and then `time + duration` and let you just figure out whatever rate you want between that.  This sort of sounds like the `mtime` type stuff, but I think some applications you prefer to have this process start at some regular, dose-like intervals.

**Comment by kylebmetrum** [comment]
@billdenney In your model, how do you tell when (`TIME` or `SOLVERTIME`) the infusion rate changes?  Is rate just changing as some function of time after the dose was started?

**Comment by billdenney** [comment]
> In your model, how do you tell when (TIME or SOLVERTIME) the infusion rate changes?

Currently, it looks something like the following in abbreviated form.

```
$MAIN
  // Record the dosing time
  if (NEWIND < 2) {
    double TDOSE = -9999;
    double DOSEEND = -9998;
    double DOSERATE = 0;
  }
  if ((self.evid == 1 || self.evid == 4) && doseratebase > 0) {
    TDOSE = self.time;
    DOSEEND = self.time + self.amt/doseratebase;
    DOSERATE=doseratebase;
  }
  F_CENT = 0;

$ODE
  // MAXADS is the maximum amount that can adsorb and ADS is the current amount adsorbed
  double ADSRATE = KADS*(MAXADS - ADS)/MAXADS
  if (TDOSE <= SOLVERTIME && SOLVERTIME <= DOSEEND) {
    RATEIN = DOSERATE - ADSRATE;
  }
```

**Comment by billdenney** [comment]
FYI, your suggestion with `EVID == 9` worked just like I needed it.
