### ISSUE TITLE
Cannot Use ETA in $ODE

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#359]
When using an ETA value directly in the $ODE block,  I got the following error (modified to blind the original code):

```
C:/Users/BILLDE~1/DOCUME~1/R/WIN-LI~1/3.4/mrgsolve/base/modelheader.h:124:18: error: 'self' was not declared in this scope
 #define _xETA(a) self.ETA[a-1]
                  ^
mod55-mread-source.cpp:172:20: note: in expansion of macro '_xETA'
 #define ETA_V1 _xETA(3)
                    ^
mod55-mread-source.cpp:279:29: note: in expansion of macro 'ETA_V1'
  V1   = exp(LTVV1 + ETA_V1)*pow(WTKG_current/70, EWV1);
                             ^
make: *** [mod55-mread-source.o] Error 1
```

With ignorance, I'm guessing that there is a rational reason that you shouldn't be able to directly access ETA values (or apparently self.*) while in $ODE.  But, if reasonable, it would help to give a more direct error message than the one above.  Perhaps something could be given at parse time?  (If unreasonable, no worries.)

**Comment by kylebmetrum** [comment]
@billdenney That error message is coming from the compiler.  We don't check the code for things like using ETA in `$ODE` and so far the strategy has been to just let the users deal with these messages.  We could start trying to inspect the code and help out here, but I haven't gone down that road yet b/c I'm not sure I can (or want to) get it to the place where we will make sure we intercept any and every syntax error.  I agree that this isn't very satisfying and I usually end up apologizing to everyone about it ... while also reminding everyone of the great flexibility you get in return.  

One thing that I can do here is to get to work on the user guide to be clearer about what you can use where. 

The other thing I'll do sooner rather than later is to move the ETAs out of the `self` object ... they don't need to be in there and, while it won't fix the error message, it might make it easier to follow what the complier is telling you.

**Comment by kylebmetrum** [comment]
This will likely stay as is.
