### ISSUE TITLE
Question:  What is the best way to capture a value in the $ODE section?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#360]
In some of my code, it would be helpful to capture the body weight that needs to be dynamic during the study.  Specifically, I'm doing something like:

```
$ODE
  double WT_current = SOLVERTIME*WT_slope + WT_baseline;
```

I can redo the calculation of `WT_current` outside of the `$ODE` block, but I'd prefer to do something like:

```
$ODE
  capture WT_current = SOLVERTIME*WT_slope + WT_baseline;
```

What is the best practice to extract a value calculated only in the $ODE block?  Is there a way that I can directly assign to a compartment (rather than `dxdt_CMTNAME`) and get it out that way?

**Comment by kylebmetrum** [comment]
@billdenney You can still just capture that.  As you probably found out, I went out of my way to make it so that you can't use `capture` in `$ODE`.  Initially, there was concern that the solver doesn't stop right at the "integrate-to" time and that the calculation wouldn't be consistent with the value you'd get if you re-calculated in `$TABLE`.  I ended up making another call to `$ODE` after the system advances, so maybe it isn't relevant anymore.  But you can easily list the variable name in `$CAPTURE` and get the value. 


```r
> code <- '
+ $PARAM INTERCEPT = 10
+ 
+ $CMT BAR
+ 
+ $ODE
+ double FOO = INTERCEPT + SOLVERTIME;
+ 
+ dxdt_BAR = 0;
+ 
+ $TABLE
+ capture FOO2 = INTERCEPT + TIME;
+ 
+ $CAPTURE FOO
+ '
> 
> mod <- mcode_cache("foo", code)
Loading model from cache.
> 
> out <- mrgsim(mod, delta = 0.1)
> 
> head(out)
  ID time BAR  FOO FOO2
1  1  0.0   0 10.0 10.0
2  1  0.1   0 10.1 10.1
3  1  0.2   0 10.2 10.2
4  1  0.3   0 10.3 10.3
5  1  0.4   0 10.4 10.4
6  1  0.5   0 10.5 10.5
> tail(out)
Model:  foo 
    ID time BAR  FOO FOO2
236  1 23.5   0 33.5 33.5
237  1 23.6   0 33.6 33.6
238  1 23.7   0 33.7 33.7
239  1 23.8   0 33.8 33.8
240  1 23.9   0 33.9 33.9
241  1 24.0   0 34.0 34.0
> 
> summary(out$FOO - out$FOO2)
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
      0       0       0       0       0       0 

```

**Comment by billdenney** [comment]
Sorry for the delay.  That works for me.  Thanks!
