### ISSUE TITLE
DLSODA Overshoot

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#369]
To illustrate what is being discussed on NMUSERS (05/04/2018):

- __The setup__: simulate a 10 hour infusion; stop the simulation right at the end of the infusion
- The simulation runs to 10 hours (the end of the infusion), but the solver will "overshoot" that 
time (`10.137309` in this case) and therefore `Cmax` will be higher than the concentration at the 
end of the infusion
- The overshoot isn't in the official solution (see `CENT`); rather, it is in the our "hack" of the ODE block to try to calculate Cmax/Tmax (`amax` and `maxt` in the  ODE example here)
- This is expected behavior

``` r
library(mrgsolve)
```

# Model with ODEs

``` r
code <- '
$CMT CENT

$GLOBAL
double maxt = 0;
double amax = 0;

$ODE
if(SOLVERTIME > maxt) maxt = SOLVERTIME;
if(CENT > amax) amax = CENT;

dxdt_CENT = -0.05*CENT;

$CAPTURE maxt amax
'

mod <- mcode_cache("cmax", code)
#> Compiling cmax ... done.

out <- 
  mod %>% 
  ev(amt = 100, rate = 10) %>% 
  mrgsim(end = 10)

tail(out)
#> Model:  cmax
#>    ID time     CENT      maxt     amax
#> 7   1    5 44.23984  5.189426 45.70813
#> 8   1    6 51.83636  6.426397 54.96175
#> 9   1    7 59.06238  7.663367 63.66038
#> 10  1    8 65.93599  8.900338 71.83731
#> 11  1    9 72.47437 10.137309 79.52383
#> 12  1   10 78.69387 10.137309 79.52383
```

The apparent maximum time (hacked from the ODEs) was greater than the actual simulation time.  This is "overshoot" by the solver.  Accordingly, the apparent maximum amount in the system (`amax`, again hacked from the ODEs) is greater than the amount in the system at the end of the infusion and the end of the simulation.   We see these results precisely because we did hack the ODEs to try to figure out Cmax.  But the "official" answer (`CENT`) is as we expect and doesn't differ when we calculate with an analytical solution (below).

# Model with analytical solution

``` r
code <- '
$PKMODEL cmt = "CENT"
$PARAM CL = 1, V = 20
'

mod <- mcode_cache("cmax_closed", code)
#> Compiling cmax_closed ... done.

out <- 
  mod %>% 
  ev(amt = 100, rate = 10) %>% 
  mrgsim(end = 10)

tail(out)
#> Model:  cmax_closed
#>    ID time     CENT
#> 7   1    5 44.23984
#> 8   1    6 51.83636
#> 9   1    7 59.06238
#> 10  1    8 65.93599
#> 11  1    9 72.47437
#> 12  1   10 78.69387
```

Created on 2018-05-04 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

# NONMEM snippet
```
$ABB COMRES=2

Set these values to zero for each new subject:
$PK
   IF(NEWIND.LE.1) THEN
     COM(1)=0
     COM(2)=0
  ENDIF

and computed Cmax/TMAX as
$DES
  IF(CONC.GT.COM(1)) THEN
        COM(1)=CONC
        COM(2)=T
  ENDIF

$ERROR
CMAX=COM(1)
TMAX=COM(2)
```

**Comment by smouksassi** [comment]
for what is worth now nonmem ship with an example with root finder refer to :
cmax14.ctl in examples folder it shows how to use a root finder

...

$DES

   DADT(1)=-KA*A(1)
   DADT(2)= KA*A(1)-KE*A(2)


$ERROR
include nonmem_reserved_general

TMAX=0.0
CMAX=0.0
ZRCROSSDIR=0 ; ZERO CROSSING DIRECTION
CMAXDER=0.0
; THIS ROOT-FINDER CAN FIND THE EXACT TMAX AND CMAX, BY FINDING WHEN DADT(2) IS ZERO
; SEE SUBROUTINE FCVROOTFN in cmax14u.f90
 IF(RTSIGNAL>0.0) THEN ; A ZERO-CROSSING HAS BEEN FOUND
  TMAX=TRTINFO(1) ; ONLY ONE CROSSING EXPECTED, SO INDEX IS 1
  CMAX=YRTINFO(2,1)/S2 ; PICK UP THE Y(2) VALUE AT CROSSING NUMBER 1
  CMAXDER=YPRTINFO(2,1); VERIFY THAT CMAX DERIVATIVE IS CLOSE TO ZERO.
  ZRCROSSDIR=RTINFO(1,1) ; VERIFY THAT ZEROCROSSING IS IN NEGATIVE DIRECTION (-1, FROM POSITIVE TO NEGATIVE), INDICATING A PEAK, RATHER THAN A NADIR
 RTSIGNAL=0
 ENDIF

; Compare with analytical solution for tmax, cmax
CMAXC=0.0
TMAXC=0.0
IF(AMT>0.0) THEN
  TMAXC=LOG(KA/KE)/(KA-KE)
  CMAXC=KA*AMT/S2*(EXP(-KE*TMAXC)-EXP(-KA*TMAXC))/(KA-KE)
ENDIF

code in:
cmax14u.f90
