### ISSUE TITLE
Official Shiny App?

### ISSUE THREAD

**Issue by billdenney** [metrumresearchgroup/mrgsolve#422]
As I get this question for PKNCA often enough, I'm going to go ahead and beg forgiveness before I start, but...

Is there an official Shiny app that works generically with mrgsolve?  The follow on if no would be: "Should there be?"

I ask because I've probably written about 4 of them over time, and I'd like to start from a better, more generic, starting place and make the tweaks that I need rather than starting from scratch.  When I've made them, there seem to be a similar set of functionality between the ones that I've made.  If we collaborate to make a single good one, it would both save a lot of people time (within the mrgsolve-using, Shiny-app-making universe) and we would likely have a better product for our work.

In general, the features that I see as common for the models that I write are:

To run:
* Input the model (e.g. the ".cpp" file or compiled model object); usually fixed within one app but maybe a set of models would be good

UI:
* Inputs
    * Update dosing (in a fully general way, you may dose to different compartments with different schedules, and different amounts and the schedule may not be a simple repeat)
    * Update parameters (either number entry or sliders)
        * Optionally including IIV and residual variability in parameters that update.
    * Select for a parameter set (e.g. mouse parameters or human parameters)
    * Optional: Input observed data to include in plots
    * Run simulation
* Outputs
    * Plot the simulation results (some or all of the output compartments and values, UI to select which ones)
        * Include observed data, if applicable
        * Calculate confidence intervals, if applicable
    * Summary calculation results on the simulation results (hard to generalize, but a placeholder could be inserted for how to do it)

To be clear:  I don't think that this code would belong as part of `mrgsolve` itself, but it may be a partner package or a suggested starting script in the documentation.

**Comment by kylebmetrum** [comment]
Hi @billdenney - 

If I'm understanding this right, this would be a shiny app that could (more or less) work with any model?  Or at least more so than an app that was created to tap into features of one specific model?

We have a couple of projects like that going but nothing that we could release ourselves. 

If this is what I think it is, a good starting place would be ModViz from Merck (@vaddadyp).  From what I understand, will be public sooner rather than later.  Maybe pending publication first, not sure. 

![screen shot 2018-12-10 at 4 56 10 pm](https://user-images.githubusercontent.com/16908301/49767080-c2513600-fc9c-11e8-9bdd-ff256d2489da.png)

The app has been demonstrated in the public before (ACoP 8?) and looks really good. 

Kyle

**Comment by billdenney** [comment]
Ah, you're right!  ModViz is probably the right tool for the job.  I'm looking forward to it @vaddadyp!
