### ISSUE TITLE
Segfault when infusion with rate > 0 and amt=0

### ISSUE THREAD

**Issue by kylebmetrum** [metrumresearchgroup/mrgsolve#43]
There also seems to be a threshold when rate >> amt that causes the segfault.

Seems reasonable to require positive amount when rate is non-zero.  And maybe some minimum duration for the infusion (it would be very small)?

**Comment by kylebmetrum** [comment]
When an infusion-off record is added to the `rec_list` it is now forced to happen after the current record even if it has the same time as the current record.

**Comment by kylebmetrum** [comment]
I think this is worked out now where something like `ev(rate=100, amt=0)` won't cause your computer to blow up.  

But @vjd: wondering if we should have an error if there is a non-zero rate when `amt==0`?

**Comment by vjd** [comment]
@kylebmetrum by design, I am trying to think of examples that would require `rate>0` when `amt==0`. Where would be required such a system?

We cannot have this in terms of dosing - that is a given. Even if you have non-zero rate at a non-zero amount a lag, I guess there will probably be a delay in the system initiation and not cause an issue - right?

If we talk about PD, we usually initialize compartments with some amount, so the problem will not exist there.

**Comment by kylebmetrum** [comment]
Thanks ....

Yeah .... there should be no time when `rate > 0` and `amt==0`.  Right now, that case just does nothing ... as if no dose was given because the duration of the infusion is zero; so the infusion gets turned off as soon as it gets turned on, so no drug gets into the system.   

But seems better to not allow that to happen.   Adding an error there.
