### ISSUE TITLE
Problem when adding observed concentrations in dataset

### ISSUE THREAD

**Issue by ebanvil** [metrumresearchgroup/mrgsolve#437]
Hello,

I'm trying to model a two-compartment model with zero-order infusion with pop PK data.
The code of my model is the next one:

`$PARAM  TVCL = 5.66, TVV1 = 14.85, TVQ = 8.8, TVV2 = 8.8

$CMT CENT PERIPH

$PKMODEL ncmt=2, depot=FALSE, trans=4

$MAIN
double CL = TVCL*exp(ETA(1));
double V1 = TVV1*exp(ETA(2));
double Q =  TVQ*exp(ETA(3));
double V2 = TVV2*exp(ETA(4));

$OMEGA
0 0 0 0

$SIGMA
0

$TABLE
double IPRED = CENT/V1;
double DV = IPRED*exp(EPS(1));

$CAPTURE CL V1 IPRED DV ETA(1)`

When I try to use a dataset with no observed concentrations (only evid=1 rows), the program plots perfectly my dataset with the typical parameters values of CL, V1, Q and V2.
But when I add an observed concentration (evid=0) to my dataset, everything gets crazy, and the plot is nonsense.

For example, if a run the model with this dataset:

**ID,WT,time,cmt,amt,ii,addl,evid, DV
1,55,0,1,1000,6,6,1,0**

I get this: [https://ibb.co/kJtk58t](url)

But when I use a dataset with observed concentrations, e.g:

**ID,WT,time,cmt,amt,ii,addl,evid, DV
1,55,0,1,1000,6,6,1,0
1,55,17.5,0,0,0,0,0,25**

I get a plot like this: [https://ibb.co/cLdzXCp](url)

I've been searching in the mrgsolve documentation about datasets, but I can't find where the error is.

Any help would be fantastic.
Thank you a lot!

**Comment by kylebmetrum** [comment]
First of all ... I'm sorry for all the time that has passed since you posted.  I didn't see this one come through. 

The reason why this happens is that when mrgsolve finds one observation record in your data set, it will assume that (for the entire data set) you are using the data to say where the observations are.  So mrgsolve thinks you want the dose at time 0 and then a single observation at time 17.5.  

You could do a couple of things here: 

Stick with an event object (this is essentially just a data frame that will only accept non-observation records) and specify the observation times through the model time grid (`start/end/delta/add`). 

Or look at the `obsonly` argument to mrgsim; this will add the time grid in addition to the observations in the data set.  This isn't the default because it can alter the way that the system advances __when you have time-varying covariates __ or other time-varying inputs. 

Or you can do the work to code all of your observations into the data set. 

Here's an example:  __NOTE__ this comes from the github version of mrgsolve, not the one on CRAN.  You'll need that dev version to get `expand_observations`. 



``` r


library(mrgsolve)

code <- '
$PARAM TVCL = 5.66, TVV1 = 14.85, TVQ = 8.8, TVV2 = 8.8

$CMT CENT PERIPH

$PKMODEL ncmt=2, depot=FALSE, trans=4

$MAIN
double CL = TVCL*exp(ETA(1));
double V1 = TVV1*exp(ETA(2));
double Q =  TVQ*exp(ETA(3));
double V2 = TVV2*exp(ETA(4));

$OMEGA
0 0 0 0

$SIGMA
0

$TABLE
double IPRED = CENT/V1;
double DV = IPRED*exp(EPS(1));

$CAPTURE CL V1 IPRED DV ETA(1)
'

mod <- mcode("observation", code)
#> Building observation ... done.

data <- expand.ev(amt = 1000, ii = 6, addl = 6, WT = 55, DV = 0)
data
#>   ID  amt ii addl WT DV evid cmt time
#> 1  1 1000  6    6 55  0    1   1    0

mrgsim_d(mod,data) %>% plot()
```

![](https://i.imgur.com/ZLbsHTn.png)

``` r

data2 <- expand_observations(data, times = 17.5)

data2
#>   ID  amt ii addl WT DV evid cmt time
#> 1  1 1000  6    6 55  0    1   1  0.0
#> 2  1    0  0    0 55  0    0   0 17.5

mrgsim_d(mod,data2) %>% plot()
```

![](https://i.imgur.com/F2JKOy8.png)

``` r

mrgsim_d(mod,data2, obsaug = TRUE) %>% plot()
```

![](https://i.imgur.com/Hgqf0Hi.png)

<sup>Created on 2019-01-21 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kylebmetrum** [comment]
This is discussed in the user guide here
https://mrgsolve.github.io/user_guide/input-data-sets.html#two-types-of-data_set

**Comment by ebanvil** [comment]
Hello Kyle,
Thank you a lot for all the information!
I've got it using the obsaug=TRUE parameter. You say: "This isn't the default because it can alter the way that the system advances __when you have time-varying covariates __ or other time-varying inputs." 
How does the obsaug=TRUE affect if I use time-varying covariates?

Thank you a lot for the help!

Regards

**Comment by kylebmetrum** [comment]
It's because mrgsolve uses `next-observation-carry-backward` as the default.  And this can only be based on what is in the data set.   The "phantom" records that mrgsolve inserts when `obsaug=TRUE` hang on to the previous actual data set row rather than looking ahead to the next.  We could have the other behavior (preferred, I know) with some refactoring.  But as it stands now, there will be some differences.  

If you really need precise control over what happens, I'd put the records into the data set and there will be no question about what happens.  Otherwise, there is an option to set `nocb=FALSE` which will switch to `locf`-type advance.  But I'd advise working out a concrete example and checking your specific problem to make sure it is working as you expect.

Kyle
