### ISSUE TITLE
Inconsistency's predictions when adding dataset of observations

### ISSUE THREAD

**Issue by johannlaurent** [metrumresearchgroup/mrgsolve#445]
Hello and thanks for the great work!
Here the issue:
# Inconsistency's predictions when adding dataset of observations
## At the same timepoint you don't get the same result when adding extra records with data_set option.  Here the different is tiny but in some real examples it is huge. 

#Please see below the example:

library(dplyr)
library(mrgsolve)

mod <- mrgsolve:::house()

data(extran1)
head(extran1)

extran1_ID3 <- extran1 %>% filter(ID==3)

data_sim1 <- data.frame(ID=3,amt=0, cmt=2, time=seq(0,10,by=0.01),  addl=0, ii=0, rate=0, evid=2)

data_sim2 <- data.frame(ID=3,amt=0, cmt=2, time=seq(0,10,by=1),  addl=0, ii=0, rate=0, evid=2)

extran1_ID3_1 <- bind_rows(extran1_ID3, data_sim1) %>% 
  arrange(ID, time, cmt, evid) %>% as.data.frame() 

extran1_ID3_2 <- bind_rows(extran1_ID3, data_sim2) %>% 
  arrange(ID, time, cmt, evid) %>% as.data.frame() 

set.seed(1234)
out1 <- mod %>% 
  data_set(extran1_ID3_1) %>% 
  carry_out(cmt, a.u.g, evid) %>% 
  obsaug %>% 
  mrgsim(end=10, delta=1) %>% 
  as.tbl 

set.seed(1234)
out2 <- mod %>% 
  data_set(extran1_ID3_2) %>% 
  carry_out(cmt, a.u.g, evid) %>% 
  obsaug %>%  
  mrgsim(end=10, delta=1) %>% 
  as.tbl 
  
  out1 <- out1 %>% filter(a.u.g==0 & time %in% seq(0,10,by=1))
  out2 <- out2 %>% filter(a.u.g==0 & time %in% seq(0,10,by=1))

 #Compare differences
library(arsenal)
comp <- compare(out1,out2)
comp
summary(comp)
diffs(comp)

comp <- compare(out1,out2,tol.num.val = 0.00001)
comp
summary(comp)
diffs(comp)

**Comment by johannlaurent** [comment]
Thanks a lot for swift reply, much appreciated. Yes you are totally right here in the example replacing evid=2 by  evid=0 in the data_sim you don't have the issue. 

However it is typically the same kind of issue I am facing with other models. 
And I just figured that it seems to come from the OMEGA and SIGMA. 
Here in the example it is set to 0. But what if OMEGO and SIGMA are not equal to 0, by fixing the seed, should you be able to get the same result? Or I am certainly missing something. 
Thanks again

**Comment by johannlaurent** [comment]
Indeed it is coming from the SIGMA. OMEGA can be changed and you will get the same result. 
For the test, in the mrgsolve:::house() model I have set SIGMA to 1 and I have a different DV results but all other parameters are totally equal. 
Thanks a lot again for this great package!

**Comment by kylebmetrum** [comment]
@johannlaurent The difference in the original example is definitely due to event records and the solver.  

You can verify this by changing:

```r
mod <- mrgsolve:::house()
```
to 

```r
mod <- mread("pk1", modlib()) 
```

The new model doesn't use the ODE solver but rather does the computation in closed form; you get the same result regardless evid on the observation records. 

I did make a tweak to the docs to emphasize that. 

But ... yes, you will __definitely__ see different results when you do this type of exercise when there are residual error random effects involved.  There is no way to replicate the simulated EPS values when you start changing the number of observation records in the data set.  For the random result to be reproducible, you really need to have the same design.  


Here's a little vignette that I made the other week to look at this.  I believe ETA is reproducible when the number of subjects stays the same but the number of observations is different.  I think it should be but I usually tell people that the input needs to be the same to get reproducible random results.

``` r
library(mrgsolve)
library(dplyr)


code <- '
$OMEGA 1 1 1 1
$SIGMA 1
$CAPTURE ETA(1) ETA(2) ETA(3) ETA(4) EPS(1)

'
mod <- mcode("eta", code)
```

``` r
set.seed(1013)
a <- mrgsim(mod, end = -1, nid = 100) %>% as_tibble() %>% distinct(ID, .keep_all= TRUE)
```

``` r
set.seed(1013)
b <- mrgsim(mod, end = 100, nid = 100)  %>% as_tibble() %>% distinct(ID, .keep_all= TRUE)
```

``` r
set.seed(1013)
c <- mrgsim(mod, end = -1, nid = 100)  %>% as_tibble() %>% distinct(ID, .keep_all= TRUE)
```

# Same seed, more observations, just ETAS

``` r
identical(a[,seq(6)], b[,seq(6)])
#> [1] TRUE
```

# Same seed, more observations, include EPS

``` r
identical(a,b)
#> [1] FALSE
```

# Same seed, same observations, include EPS

``` r
identical(a,c)
#> [1] TRUE
```

<sup>Created on 2019-01-31 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by kylebmetrum** [comment]
@johannlaurent I think we both posted the last one at the same time.  You're seeing the same thing that I posted. 

Thanks for raising the issue and helping us to clarify.  Don't hesitate to bring any questions up here ... it helps a lot when people ask. 

Kyle

**Comment by johannlaurent** [comment]
Thanks a lot @kylebmetrum ! 
Please close the issue. 
And thank you so much for your fast reply and support. 
Johann
