### ISSUE TITLE
Model using $PRED: how to change the independent variable

### ISSUE THREAD

**Issue by sbihorel** [metrumresearchgroup/mrgsolve#451]
Hi,

Let's say I want to simulate an exposure-response model. TIME would not be the appropriate independent variable, so I would have to define something like "double EXPOSURE = TIME;" in the $GLOBAL or $PRED.
I did not see a way to request a variable name change in ?mrgsim. Is there an alternative way to control what is the independent variable name for simulation?

**Comment by kylebmetrum** [comment]
Is this what you want to do?
https://mrgsolve.github.io/blog/2018-pred.html#3_pkpd_model

You don't have to get time involved in the simulation.

**Comment by sbihorel** [comment]
Thanks Kyle

The link you sent describes the situation where a simulation dataset is provided in the mrgsim call. I think my question relates more to the situation where no dataset is provided in the mrgsim call.

**Comment by kylebmetrum** [comment]
> Is there an alternative way to control what is the independent variable name for simulation?

No.  The only time I can think of where this would make a difference is in the default plot method

The plot method assumes the independent variable is TIME.  Use the formula if you want to plot versus something else.

```r
dollar_pred_model %>% 
  mrgsim() %>%
  plot(RESPONSE ~ AUC)
```

I guess you might possibly want the independent variable to be automatically included in the output.  You can just use `carry_out` or `$CAPTURE`. 

I could imagine this

```c
[ PRED ] @independent_variable EXPOSURE

capture RESPONSE = f(EXPOSURE);
```

And then have `EXPOSURE` automatically get captured into the output and start tracking what the independent variable is so that the plot method is automatically right.

For now, we'll just have to follow the example that exists.

**Comment by sbihorel** [comment]
I understand. I am just exploring what is possible :)

**Comment by kylebmetrum** [comment]
Ok.
