### ISSUE TITLE
Transit compartments - how to use a loop to write ODEs? 

### ISSUE THREAD

**Issue by zackwjones** [metrumresearchgroup/mrgsolve#464]
I know a similar issue was addressed in [https://github.com/metrumresearchgroup/mrgsolve/issues/423](url), but unfortunately I couldn't quite understand the solution provided (specifically why an alias has to be used?) . I'm simply trying to use a loop to create ODEs for several transit compartments. Here is a code snippit: 

```
[PARAM] @annotated

kin: 1
SC50: 0.0520 
Tp: 142 : h
Smax: 11.2
Np: 10
C: 10

[CMT] @annotated

P1: precursor first age compartment 
P2: second age compartment
P3: third age compartment
P4: fourth age compartment
P5: fifth age compartment
P6: sixth age compartment
P7: seventh age compartment
P8: eighth age compartment
P9: ninth age compartment
P10: tenth age compartment

[ODE]
dxdt_P1 = kin*(1+Smax*C/(SC50+C))-Np/Tp*P1

// transit compartments for remaining precursor compartments
for(int i = 1; i <= Np; i++) {
_DADT_[i] = Np/Tp*(_A_[i-1]-_A_[i]);
}
```

Does _DADT_[1] represent compartment P2, and does _A_[0] represent the amount in P1? Is this the proper way of doing this? Is there a way to print out the ODEs generated from this loop to confirm?

Additionally, is there a way to write a loop to define / initialize the compartments as well?

**Comment by kylebmetrum** [comment]
Hi @zackwjones - 

I'm happy to help out to answer questions on this.  But please remember that this is poking under the 
hood in a way that by-passes the official interface.  So doing the loop might be better than coding 
every equation explicitly but there might be some pain points / inconvenience that might come along
with it too.  

 - `_DADT_[1]` is the equivalent to `dxdt_P1`, but for the second compartment (the indexing starts 
   at zero)

- `_A_[0]` is the amount in the first compartment (`P1` in this example); that's right

The loop is the model code here; it doesn't get turned into a series of equations; this is all there is.  
There is a way to write a loop to initialize compartments (have the compartment start at some 
non-zero value), but not to declare them (say what the names of the compartments are).  Use
`_A_0_[n] = 1;` in `$MAIN` to set an initial value. 

You can see the names of the data structures here:
https://github.com/metrumresearchgroup/mrgsolve/blob/master/src/housemodel-mread-source.cpp#L56-L64

I'm not sure on the alias part of the question.  One thing I did in that code was to 
show how you can get the number of a compartment given the name of a compartment.  That 
just generalizes the code so that your transit system could get shuffled in the 
compartment order and the loop to run the differential equations would be preserved.  That
isn't necessary to do. 

Anyway ... I've been thinking about coding all of this into the model specification interface since
Bill asked the question (it would be nice if / when needed).  It's helpful to have discussions like
these to see what needs to get done, where we can save effort, etc. 

I do think I will add syntax to mass declare a series of compartments (something similar to the 
$THETA block).  

Please let me know if the code isn't running or if we can help with specific issues here.

Thanks,
Kyle

**Comment by zackwjones** [comment]
@kylebmetrum 

Thank you so much for a quick and detailed response. I too have wondered what other issues may come up by 'poking under the hood'. At the end of the day, it doesn't take much time to just copy/paste these ODEs and make the minor changes by hand as opposed to trying the more programmatic approach with a loop. The time saved is minimal for this specific problem, so staying within the official interface is probably the correct approach.

The link to the C++ code was really helpful. 

I'll check back in if I run into any specific issues - thanks again!
