### ISSUE TITLE
How do we set the compartment amount to stay >= 0?

### ISSUE THREAD

**Issue by sueinchoi** [metrumresearchgroup/mrgsolve#488]
Hi
First, love your work!

Second, I have one question!
When my differential equation of absorption compartment is like

dxdt_GUT= -k1*GUT - k0;

then, it goes to below the zero after a certain time point, which is true in mathematically but not in physiologically. 

Is there any way to make the amount of GUT compartment stay 0 after a certain time point or option to make them always keep stay above 0 as NONMEM does? (Especially when it is minus..)

Thank you for your support!

**Comment by kylebaron** [comment]
Hi @sueinchoi  - 

My guess is that you will have to split the administered dose and have a certain fraction getting administered to `GUT` and another fraction getting administered as zero order infusion (`k0`).  

I could help you with that code if that's what you want to do.

Otherwise, if you have some NONMEM code that guarantees that GUT doesn't go negative with the ODE that you wrote, please share it and I can help you do that in mrgsolve too.

Kyle

**Comment by sueinchoi** [comment]
@kylebaron 

Thank you for your answer. We split them as you said and it was helpful.
Btw is there any way I can put the 'if' inside the code like ,,, this below?

if(time < 24) dxdt_GUT = -k1 * GUT - k0;
if(time > 24) dxdt_GUT = 0

and also, whenever i try to change the parameter of model using  **param**
like param(mod, TVKA = 2, TVCL = 5, TVVC = 20)
the output is 

![image](https://user-images.githubusercontent.com/48196612/61861384-c6b62080-af06-11e9-80e2-9cef39351a8a.png)

and parameter did not change.. besides this, everything works really well.

Thank you for your support always.

**Comment by kylebaron** [comment]
@sueinchoi 

Yes you can do that; the syntax would be something like

```
[ ode ] 

if(SOLVERTIME < 24) {
  dxdt_GUT = -ka*GUT - k0;
} else {
  dxdt_GUT = 0;
}
```

Use `SOLVERTIME` rather than `time`.


This would only work for the first dose, but we could change so that absorption "turns on" at the time of dose and "turns off" after 24 hrs. 

I'm guessing you could / should also use an mtime here too:

```
[ main ] 
double mt = self.mtime(24);
```

This just forces the problem to stop and restart at 24 hours (the time that the absorption changes) and the discontinuity will be handled properly.  

Happy to keep helping out with ideas for this.
