### ISSUE TITLE
easier way to create dosing scenario

### ISSUE THREAD

**Issue by vjd** [metrumresearchgroup/mrgsolve#49]
is there a more efficient way to code this specific dosing scenario -
1 or 2 IV loading doses with variable infusion durations followed a PO maintenance dose. This is my current implementation for this:

```
iv_dose1 <- expand.ev(amt=c(40000),cmt=2,rate=-2, time=0, LINF=1) %>% mutate(dose=c(40))
iv_dose2 <- expand.ev(amt=c(20000),cmt=2,rate=-2, time=1, LINF=0.5) %>% mutate(dose=c(20))
iv_dose3 <- expand.ev(amt=c(20000),cmt=2,rate=-2, time=1.5, LINF=0.5) %>% mutate(dose=c(20))
po_dose <- ev(ID=1,amt=rep(160000,8),time=c(2,seq(12,84,12)), cmt=1, rate=0, LINF=0) %>% as.data.frame %>% as.tbl %>% 
  mutate(dose=c(160))
data <- bind_rows(iv_dose1,iv_dose2,iv_dose3,po_dose)
```

**Comment by kylebmetrum** [comment]
library(mrgsolve)
    library(dplyr)

Note
====

I think this is a really good question: a big part of the convenience is
being able to easily assemble a data set for a complicated simulation.
The harder it is to do that, the convenience starts to drop off.

Always looking for new functions to automate what you want to do.
`expand.ev` can be helpful, but really not in a case like this.

See the `as_data_set` function below. I don't think it greatly helps
this problem but I'm always looking to do that sort of thing: a function
that takes simple input and assembles it into a working data set
according to some assembly assumptions.

Previous
========

    iv_dose1 <- expand.ev(amt=c(40000),cmt=2,rate=-2, time=0, LINF=1) %>% mutate(dose=c(40))
    iv_dose2 <- expand.ev(amt=c(20000),cmt=2,rate=-2, time=1, LINF=0.5) %>% mutate(dose=c(20))
    iv_dose3 <- expand.ev(amt=c(20000),cmt=2,rate=-2, time=1.5, LINF=0.5) %>% mutate(dose=c(20))
    po_dose <- ev(ID=1,amt=rep(160000,8),time=c(2,seq(12,84,12)), cmt=1, rate=0, LINF=0) %>% as.data.frame %>% as.tbl %>% 
      mutate(dose=c(160))
    data <- bind_rows(iv_dose1,iv_dose2,iv_dose3,po_dose)

Improved (???)
==============

    iv <- ev(amt=c(4,2,2), cmt=2,rate=-2, time=c(0,1,1.5), LINF=c(1,0.5,0.5))
    po <- ev(amt=rep(16,8),time=c(2,seq(12,84,12)), cmt=1, LINF=0)
    doses <- as.data.frame(iv+po) %>% mutate(dose = amt*10,amt=amt*10000,ID=1)

Check
=====

    doses <- doses %>% dplyr::select_(.dots=colnames(data))

    identical(as.list(doses), as.list(data))

    ## [1] TRUE

`as_data_set`
=============

I just added this as a way to get different "arms"

    df <- as_data_set(iv,po) 

    df

    ## Source: local data frame [11 x 7]
    ## 
    ##       ID  time   cmt  evid   amt  rate  LINF
    ##    (dbl) (dbl) (dbl) (dbl) (dbl) (dbl) (dbl)
    ## 1      1   0.0     2     1     4    -2   1.0
    ## 2      1   1.0     2     1     2    -2   0.5
    ## 3      1   1.5     2     1     2    -2   0.5
    ## 4      2   2.0     1     1    16     0   0.0
    ## 5      2  12.0     1     1    16     0   0.0
    ## 6      2  24.0     1     1    16     0   0.0
    ## 7      2  36.0     1     1    16     0   0.0
    ## 8      2  48.0     1     1    16     0   0.0
    ## 9      2  60.0     1     1    16     0   0.0
    ## 10     2  72.0     1     1    16     0   0.0
    ## 11     2  84.0     1     1    16     0   0.0

    df <- as_data_set(ev(amt=c(50,100),     time=c(0,24), ID=1:3), 
                      ev(amt=c(100,300,50), time=c(0,24,48), ID=1:3))

    df

    ## Source: local data frame [15 x 5]
    ## 
    ##       ID  time   cmt  evid   amt
    ##    (dbl) (dbl) (dbl) (dbl) (dbl)
    ## 1      1     0     1     1    50
    ## 2      1    24     1     1   100
    ## 3      2     0     1     1    50
    ## 4      2    24     1     1   100
    ## 5      3     0     1     1    50
    ## 6      3    24     1     1   100
    ## 7      4     0     1     1   100
    ## 8      4    24     1     1   300
    ## 9      4    48     1     1    50
    ## 10     5     0     1     1   100
    ## 11     5    24     1     1   300
    ## 12     5    48     1     1    50
    ## 13     6     0     1     1   100
    ## 14     6    24     1     1   300
    ## 15     6    48     1     1    50

this is different than `expand.ev` because you can have more compilcated
regimens and mrgsolve numbers the IDs for you. then just mutate away to
clean it up

**Comment by vjd** [comment]
This is helpful. I realized while preparing this dosing set that `ev` is more helpful than `expand.ev`, but was confused about the difference in the return values of the two functions - `ev` returns a S4 object whereas `expand.ev` returns a data frame? Would like to learn a couple of more things while at this topic

1. Looks like the return value of `ev` is an S4 object with a dataframe of the doses. Is it just for `mrgsolve` S4 objects or in general any S4 objects that you can add `+` them together as you did in `as.data.frame(iv+po)`. I've seen this sort of addition in other `mrgsolve` examples, but not anywhere else. 

2. `as_data_set` is a way to add "arms" - are the "ID's" the arms for each set ?

**Comment by kylebmetrum** [comment]
1. Right .... `ev` returns S4 but all it is is a data frame.  It has a class only so that we can define operations for the different elementary ev objects (it's mainly `+` and `%then%` now.  There used to be more before we switched to using `%>%`).  But the other thing that `ev` and `expand.ev` give you is some defaults to save some typing: `time=0`, `cmt=1`, `evid=1` etc.  And `expand.ev` is not that much more than `expand.grid` ... it gives you all combinations but also the defaults (like `cmt`, etc).  It is really helpful if that is what you want to do (sometimes it is sometimes no).  Definitely `ev` is more flexible ... Regarding the `+` operator: it doesn't seem quite right now.  I think it should be `c` instead ... so you can do `c(ev1,ev2,ev3)` (equivalent to `(ev1+ev2+ev3)` etc and combine a bunch of elementary objects into a complicated regimen ... it's actually in there now: https://github.com/metrumresearchgroup/mrgsolve/blob/master/rdev/R/Ops.R#L51  It needs some testing. 
1. The `as_data_set` uses one `ev` object for each "arm".   And note that this `ev` object __could__ be a complicated set of doses / interventions.  But the "arm" concept means that a specific number of IDs can get assigned to each `ev` intervention.  The bulk of what `as_data_frame` does is go through and re-number the IDs so that it's not one person getting all of the interventions or each row in the data set being a different person (what is what `expand.ev` assumes).  It (hopefully) assigns a given number of IDs to each `ev` not matter how complicated it is.
