### ISSUE TITLE
Questions on Generate MAP Bayes Parameter Estimates

### ISSUE THREAD

**Issue by wayne200240** [metrumresearchgroup/mrgsolve#492]
Hi Kyle 

I hope you are well. I am tyring to figure out a way to perform Bayesian estimation of PK parameters following the acquisition of plasma drug concentrations to individualize therapy. I went through the MAP Bayes Parameter Estimates Tutorial but is having trouble understanding parts of the code. I am relatively new to modelling and simulation world, so please forgive my naïve question. 

I don’t really understand this part of the tutorial. How did you determine the initial estimates for ETA1 and ETA2? I only have the serum concentration data. Is there a way to calculate the associated ETA values using only serum concentration data and a PopPK model? 

Thank you very much, 

5.2 Initial estimate
Note again that we are optimizing the etas here
init <- c(ETA1=-0.3, ETA2=0.2)

https://mrgsolve.github.io/blog/map_bayes.html

**Comment by kylebaron** [comment]
HI @wayne200240  - 

The initial estimates are really arbitrary here.  A "better" guess might have been some very small number close to zero, since the ETA is normally distributed with mean 0 (so, start off assuming that the individual you are fitting is just "typical").  I think I was actually trying to be a bit extreme here, just to show that the optimizer could move "bad" initial guess to the right answer.  

In the map bayes example, the optimizer is just searching the parameter space to find ETA1 and ETA2 that are consistent with the individual's data (just like fitting parameters in a non-hierarchical model);  the fixed effects + omega matrix  just forms a prior and the estimates will shrink back to the expected value of the prior depending on information content, magnitude of omega and sigma etc.  So, if your data is poorly informative for CL and VC (ETA1 and ETA2), then the estimate will just shrink back toward the typical value.  But if you do have data that is informative, then the estimate will get closer to the "true" individual value.  The other factor in this is sigma (the residual error variance), with higher residual error pushing the estimate back to the prior as well (qualitatively similar to uninformative data).

So, if you have serum concentration data and a popPK model, you should be able to estimate ETA (CL and V for example).  The estimate you get will always be a shrinkage estimate (shrinking to the mean), so (depending on information content in the data and omega and sigma) don't be surprised if the prediction based on the final estimates is some compromise between the "typical" (population) profile and the profile of the individual you are concerned with. 

Does that help with your question?  Typing this out early-ish while on vacation (but I've already had my coffee so I can't use that as an excuse).  Let me know what still needs clarification.

KTB

**Comment by wayne200240** [comment]
Hi @kylebaron 

Thank you so much for your reply. I understand the concept now. I 


code <- '
$SET request =""

$PARAM  TVCLNHD = 0.372, TVV1 = 40.5, TVV2 = 38.4, Q = 4.6, CLHD = 4.16, ETA1 = 0, ETA2 = 0, ETA3 = 0

$CMT C P

$MAIN
double CLNHD  = TVCLNHD * exp(ETA1 + ETA(1));
double V1     = TVV1    * exp(ETA2 + ETA(2));
double V2     = TVV2    * exp(ETA3 + ETA(3));

$OMEGA 0 0 0

$SIGMA 0

$ODE
dxdt_C = - (Q/V1)*C + (Q/V2)*P - (CLNHD/V1)*C - (CLHD/V1)*C;
dxdt_P =   (Q/V1)*C - (Q/V2)*P; 

$TABLE
double DV  = (C/V1)*(1+ EPS(1));
double ET1 = ETA(1);
double ET2 = ETA(2);
double ET3 = ETA(3);

$CAPTURE DV ET1 ET2 ET3
'

# Compile model 
mod <- mcode_cache("map", code)


# Generate omega matrix and calculate the associated inverse omega matrix
omega <- dmat(0.795, 0.926, 0.977)

omega.inv <-solve(omega_m)

#Generate sigma matrix

sigma <- matrix(0.1849)


#MAP Bayes Estimate Function for proportional error model

mapbayes <- function(eta,y,d,m,pred=FALSE) {
  
  sig2 <- as.numeric(sigma)
  
  eta %<>% as.list
  
  names(eta) <- names(init)
  
  eta_m <- eta %>% unlist %>% matrix(nrow=1)
  
  m %<>% param(eta)
  
  if(!pred) m %<>% obsonly
  
  out <- m %>% drop.re() %>% data_set(d) %>% mrgsim
  
  if(pred) return(out %>% as.tbl)
    
  sig2j <- out$DV^2*sig2
  
  sqwres <- log(sig2j) + (1/sig2j)*(y-out$DV)^2
  
  nOn <- diag(eta_m %*% omega.inv %*% t(eta_m))
  
  return(sum(sqwres) + nOn)
  
}

#Data for dose individualization 
y <- c(500, 250, 125)

#Generate data for dose prediction 
dose = c(750)
time = c(0, 0.5, 12, 24)
dat = as.data.frame(expand.grid("dose"=dose, "time"=time))
dat = arrange(dat, time)
dat$DV = c(0, 500, 250, 125, 25)
dat$amt = ifelse(dat$time==0,dat$dose,0)
dat$evid = ifelse(dat$amt>0,1,0)
dat$ID = 1
dat$cmt = ifelse(dat$amt>0,1,0)
dat

#Perform MAP Bayes Estimate 

init <- c(ETA1=0.1, ETA2=0.2, ETA=0.3)


fit <- newuoa(init, mapbayes, y=y, m=mod, d=dat)

fit$par

**Comment by wayne200240** [comment]
Dear Kyle 

Thank you so much for your reply. It is very clear and i believe i understand the topic now. Thanks, Kind regards,

**Comment by kylebaron** [comment]
Sounds good, @wayne200240   Please be in touch in case other issues come up.
