### ISSUE TITLE
Feature: Theta labels for $NMXML

### ISSUE THREAD

**Issue by poonv** [metrumresearchgroup/mrgsolve#584]
Referencing [the user guide](https://mrgsolve.github.io/user_guide/model-specification.html#block-nmxml) and [the reference doc](https://mrgsolve.github.io/docs/reference/nmxml.html), $NMXML has the capabilities to label the OMEGAS and SIGMAS. However, this does not seem to be the case for THETAS. This functionality would be particularly useful to me when dealing with models with large numbers of THETAS.

Thanks!

**Comment by kylebaron** [comment]
Right.  Currently, it uses the value in `tname` to derive the parameter names (e.g. if `tname` is "THETA", then it is `THETA1`, `THETA2` etc).  This was mainly to allow you to pull THETAs from two different models (so you could have `THETA1` from the PK model and `theta1` or `THETA_PD1` from the PD model).

It would be easy to do this: 
- if `length(tname)` is 1, we will add numbers to the end to form the "labels" (or names); (current behavior)
- if `length(tname)` is equal to `length(THETA)` and no duplicates, we will use those names as-is (no numbers added)
- otherwise error

**Comment by poonv** [comment]
Sorry, I just wanted to confirm that

> if length(tname) is equal to length(THETA) and no duplicates, we will use those names as-is (no numbers added)

has not been implemented yet.

**Comment by kylebaron** [comment]
Right; just proposing an idea at this point;  if it seems reasonable, would be willing to implement for upcoming release.

**Comment by poonv** [comment]
Sounds fine with me! No reason to create another parameter if not necessary.

**Comment by kylebaron** [comment]
Please refer to #687
