### ISSUE TITLE
$NMXML slow for large models

### ISSUE THREAD

**Issue by timwaterhouse** [metrumresearchgroup/mrgsolve#589]
I've found $NMXML to be immensely convenient, but parsing the xml file can become slow as a model grows larger.  I have a model where the xml file is  around 300k lines, 95% of which is the covariance and correlation matrix, which I don't need.  I've found that stripping the `<nm:covariance>` and `<nm:correlation>` elements can reduce the time for `mread()` from around 1 minute to several seconds.

I'm using this code to strip out the unnecessary elements from the xml file and write the output to a "dummy" run folder that mrgsolve can read from.  I'm sure this needs to be generalised further, but would something like this be possible to implement within mrgsolve itself?

```r
# Shrink xml output file to a manageable size by removing covariance and correlation sections
shrink_xml <- function(project, run) {
  xf <- readLines(file.path(project, run, paste0(run, ".xml")))
  cov_start <- grep("<nm:covariance>", xf)
  cor_end <- grep("</nm:correlation>", xf)
  xf <- xf[c(1:(cov_start - 1), (cor_end + 1):length(xf))]
  dir.create(file.path(project, paste0(run, "_xml")))
  writeLines(xf, file.path(project, paste0(run, "_xml"), paste0(run, "_xml.xml")))
}
```

**Comment by kylebaron** [comment]
I've had the same complaint when loading large BAYES runs with `$NMXML`, but didn't think about manipulating the xml like this.  

This would be something you just do once (to create the `dummy` file) and then refer to the dummy when running `mread`? 

I've also been thinking for a while about getting this information from the `.ext` file (#509), mainly because it gets you out of having worry about xml (which isn't fool-proof) and it could be much faster (open the ext, look for the row with final estimates, split it up into THETA, OMEGA, SIGMA).  I believe it should be the same information.  The main thing that I don't think you have there is how the different OMEGA and SIGMA elements are split up into different blocks (if there is more than one $OMGEA for example).

**Comment by timwaterhouse** [comment]
Yes, right now I'm only doing this once to create the dummy file, and I use that in subsequent `mread`s.  But creating the dummy file should be quick enough that it wouldn't be noticed if it was done on each `mread`.

I like the idea of reading from the `.ext` instead.  I'm not sure what you mean about the different blocks, though.  If I have an OMEGA with multiple blocks, the full OMEGA (including the zero off-diagonals) is in both the `.xml` and `.ext` files.  Or is there more info about the blocks in the `.xml` that is missing from the `.ext`?

**Comment by curtisKJ** [comment]
@kylebaron, per the compliant with BAYES runs...FWIW no one should be loading a BAYES run with `$NMXML`. They should be working with the posteriors directly.

**Comment by timwaterhouse** [comment]
@curtisKJ I'll confess that I've been using `$NMXML` for BAYES models.  I'll certainly use the posteriors for anything involving parameter uncertainty, but I've been using this for making VPCs.  Wouldn't the medians (means? whatever NONMEM gives you) from the `.xml` file be OK for that?

**Comment by kylebaron** [comment]
@timwaterhouse that's essentially what I do too.  @curtisKJ  - I do think the BAYES run could / should be loaded with NMXML.  Part of what NMXML does is get the thetas and omegas and sigmas "into the model", so there is something there to update.  I'd say most of the time, I'm updating with draws from the posterior.  When I need to simulate from the "final model estimates", I will frequently summarize the posterior (maybe across multiple chains), update and simulate from that (that's one of the things that I do when the run ends is bring the samples together, get the posterior medians, and dump out to file).  And sometimes just go with the summary that NONMEM gives from the xml file.  Regardless, it's still very convenient and useful to use NMXML with BAYES run.

**Comment by curtisKJ** [comment]
(@timwaterhouse  and @kylebaron) The reason I don't like the XML is I'm not sure mean values (or whatever NONMEM spits out) are the best to use. The posterior could be non-normal and the mean value isn't really the best. The fact that multiple chains are run complicates it for me, too, because which one do you pick? Like you describe, I'd probably use the medians summarized across chains. I see what you're saying wrt pulling it in to make it easier to update; that makes sense. I just don't have a lot of faith in what NONMEMs giving back with BAYES so I avoid it.

**Comment by kylebaron** [comment]
@curtisKJ Understood.

**Comment by kylebaron** [comment]
See also #509

**Comment by kylebaron** [comment]
Closing this issue; we'll take #509 into validation; this issue and PR #662 are referenced.
