### ISSUE TITLE
Simulation issue due to extreme values

### ISSUE THREAD

**Issue by Wendy723** [metrumresearchgroup/mrgsolve#739]
Hi, 

After updating some parameters in the model, I had the issue below when I used the simulation code as shown below. I was able to simulate for 10 days but not longer, I have seen some extreme values when I simulated until 10 days such as 1e-15 or 1e+21. I guess the abortion of the simulation was because it could not simulate lower concentrations. I was able to do the simulation smoothly before updating the parameters. Is there any setting I can try to solve this issue? Thanks

`simdata_2.25mgQ3W8doses <- modRO_103 %>% data_set(data_2.25mgQ3W8doses) %>%
  carry.out(DV, CP, DOSE) %>%
  obsonly() %>%
        mrgsim(start=0, end=85, delta=1, atol=1E-30, maxsteps=100000)  
`

`DLSODA-  At T(=R1) and step size H(=R2), the error
      test failed repeatedly or with ABS(H) = HMIN
In above message, R1 =
[1] 8.831334e-175  1.378059e+61
DLSODA-  ISTATE (=I1) illegal.
In above message, I = 
[1] -4
DLSODA-  Run aborted.. apparent infinite loop.    
Error in (function (x, data, idata = null_idata, carry.out = character(0), : error from XERRWD`

Thanks,

Wendy

**Comment by kylebaron** [comment]
Hi @Wendy723  - 

I'm not sure what's going on in the model, but I'd double check the code, make sure the model itself can't let some wacky values through.  IMO most often this error message comes when there is some problem in the code. For example, if the model is pretty simple and you are just running the simulation out a long time, you might need to do more than lower atol ... depending on the math, you might need to check very small / negative values and make them zero (use `std::max()`). 

Assuming that the code checks out and this is happening because this model is very difficult, I'd start with lowering `hmax` to maybe 1 or 0.1 or something like that.  Then maybe lower `rtol` as well.  You might not be able to keep atol as small as it is, but I'd give it a try.  

Also - you should try updating your mrgsolve version.  Not saying that it will fix this issue, but we've gone a long way since we had that FORTRAN version of DLSODA in the package.  I think it would be a good idea to update as soon as feasible. 

Let me know if any of this helps, @Wendy723 .  Might need to talk if none if this pans out.

KTB

**Comment by Wendy723** [comment]
Thanks @kylebaron I tried the code below in a newer version (0.10.4) . It gave me message as shown below.

`simdata_2.25mgQ3W8doses <- modRO_103 %>% data_set(data_2.25mgQ3W8doses) %>%
carry.out(DV, CP, DOSE) %>%
 obsonly() %>%
 mrgsim(start=0, end=85, delta=1, atol=1E-20, maxsteps=1000000) `

` [lsoda] warning..internal t = 14.7746 and h_ = 5.52056e-16 are
        such that in the machine, t + h_ = t on the next step
        solver will continue anyway.
[lsoda] warning..internal t = 14.7746 and h_ = 5.52056e-16 are
        such that in the machine, t + h_ = t on the next step
        solver will continue anyway.
[lsoda] above warning has been issued 2 times
        it will not be issued again for this problem.
[lsoda] at t = 15.5682 and step size h_ = 1.77822e-12, the
      corrector convergence failed repeatedly or
      with fabs(h_) = hmin.
[mrgsolve] lsoda returned with negative istate: -5
  means repeated convergence failures; 
  perhaps wrong choice of tolerances.
Error: simulation terminated. `


Thanks,

Wendy

**Comment by kylebaron** [comment]
Hi @Wendy723 - 

Right; I don't think the new version would fix this.  I think you should (1) look at the code again (2) if the code is right and you aren't generating any unphysiological values (even un-intended), start to work with the solver settings that I mentioned.  

I'd be happy to take a look at the code with you if you'd like to share here or via email.

Thanks,
Kyle
