### ISSUE TITLE
"carry_out" function gives wrong results

### ISSUE THREAD

**Issue by mark0935git** [metrumresearchgroup/mrgsolve#979]
Hi Mrgsolve developer,

I found that "carry_out" function seems to generate wrong results when using step dose. "Dose" column values change to 20 and 40 after 1st and 2nd administration, respectively.

I suppose these values should retain the previous values until the new dose events. In this case, the "Dose" column values should after 6 and 12.

```
mod <- mrgsolve:::house()

Step_dose = ev(time = c(0, 6, 12),
               amt = c(10, 20, 40),
               addl = c(0,0,5), ii = c(0,0,6)) %>%
    mutate(Dose = amt)

out <- 
  mod %>%
    data_set(Step_dose) %>%
    mrgsim(carry_out=c("Dose","amt"), end=24*10, delta=3)

out
```

![image](https://user-images.githubusercontent.com/29249244/168425769-eff27474-d7cb-40a7-9260-a17c2bc11b79.png)

**Comment by kylebaron** [comment]
HI @mark0935git  - 

Thanks for the question.  mrgsolve uses a "next observation carry backward" (`nocb`) setup similar to NONMEM. So with respect to the input data, I would expect the Dose amount of 20 at time 6 to carry backward to the first record at time 0

```r
> Step_dose
Events:
  time amt ii addl cmt evid Dose
1    0  10  0    0   1    1   10
2    6  20  0    0   1    1   20
3   12  40  6    5   1    1   40
```

And this is what happens

```r
> select(out, time, amt, Dose)
# A tibble: 84 × 3
    time   amt  Dose
   <dbl> <dbl> <dbl>
 1     0     0    10
 2     0    10    10
 3     3     0    20
 4     6     0    20
 5     6    20    20
```

I agree this is tricky and for years we had it as you suggest. But it ends up being inconsistent with this nocb setup. 

You could try this `nocb` argument to `mrgsim()`

```r
> out <- 
+   mod %>%
+   data_set(Step_dose) %>%
+   mrgsim(carry_out=c("Dose","amt"), end=24*10, delta=3, nocb = FALSE)
> 
> select(out, time, amt, Dose)
# A tibble: 84 × 3
    time   amt  Dose
   <dbl> <dbl> <dbl>
 1     0     0    10
 2     0    10    10
 3     3     0    10
 4     6     0    10
 5     6    20    20
```

But you might find it easier to get what you want if you just explicitly code all dose and observation records in the input data; that way you can have control over how `Dose` advances with time; it's more work to create the data set but maybe less work in the end to get exactly what you want and being able to understand what's happening.

I'd also note that `Dose` is a little tricky here because there is an apparent disconnect with `amt`; you might just  take `amt` into the output and then fill it in in the way that makes sense.  

Finally, you might look at another package I maintain called [lastdose](https://github.com/metrumresearchgroup/lastdose) that will put the last dose amount into your simulated output; this requires some columns like `EVID` in the output, but could be helpful for what I think you want to do.

```r
> library(lastdose)
> lastdose(as.data.frame(out), time_col = "time", comments = FALSE) %>% 
+   select(ID, time, EVID, AMT, Dose, LDOS) %>% head(n = 20)
   ID time EVID AMT Dose LDOS
1   1    0    0   0   10    0
2   1    0    1  10   10   10
3   1    3    0   0   20   10
4   1    6    0   0   20   10
5   1    6    1  20   20   20
6   1    9    0   0   40   20
7   1   12    0   0   40   20
8   1   12    1  40   40   40
9   1   15    0   0   40   40
10  1   18    0   0   40   40
11  1   21    0   0   40   40
12  1   24    0   0   40   40
13  1   27    0   0   40   40
14  1   30    0   0   40   40
15  1   33    0   0   40   40
16  1   36    0   0   40   40
17  1   39    0   0   40   40
18  1   42    0   0   40   40
19  1   45    0   0   40   40
20  1   48    0   0   40   40
```

Best Regards,
Kyle

**Comment by mark0935git** [comment]
@kylebaron Thanks a lot for your thorough explanation! Problem resolved!
